import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

// ── Engine-specific input file templates ────────────────────────────
// Generates structured, ready-to-run input files for computational
// chemistry engines. Each file includes realistic parameters derived
// from the user's simulation configuration and environmental conditions.

function genORCA(inputs, env) {
  const functional = inputs.functional || 'B3LYP';
  const basis = inputs.basis_set || 'def2-TZVP';
  const task = (inputs.task || 'geometry optimization').toLowerCase();
  const molecule = inputs.molecule || 'H2O';

  let keyword = '! ';
  if (task.includes('optim')) keyword += 'OPT ';
  if (task.includes('freq')) keyword += 'FREQ ';
  if (task.includes('nmr')) keyword += 'NMR ';
  if (task.includes('single point') || task.includes('sp')) keyword += 'SP ';
  keyword += `${functional} ${basis} TightSCF`;
  if (env.solvent && env.solvent !== 'none' && env.solvent !== 'vacuum') {
    keyword += ' CPCM(WATER)';
  }

  const charge = inputs.charge || 0;
  const mult = inputs.multiplicity || 1;

  let content = `${keyword}
%maxcore 4000
%pal nprocs 8 end

* xyz ${charge} ${mult}
${molecule}
*`;

  return [{
    filename: 'orca_input.inp',
    content,
    description: `ORCA input file — ${functional}/${basis}, ${task}. Run with: orca orca_input.inp`
  }];
}

function genGROMACS(inputs, env) {
  const ff = inputs.force_field || env.forcefield || 'AMBER99SB-ILDN';
  const temp = inputs.temperature || env.temperature || 300;
  const time = inputs.simulation_time || '100 ns';
  const system = inputs.system || 'Protein in water';

  const nsteps = time.includes('ns') ? parseInt(time) * 500000 : 50000000;

  const mdp = `; GROMACS .mdp file — generated by Suttain
; System: ${system}
; Force field: ${ff}
; Temperature: ${temp} K

integrator = md
nsteps = ${nsteps}
dt = 0.002

; Output control
nstxout = 0
nstvout = 0
nstfout = 0
nstxout-compressed = 5000
nstenergy = 5000
nstlog = 5000

; Bond parameters
continuation = yes
constraint_algorithm = lincs
constraints = h-bonds
lincs_iter = 1
lincs_order = 4

; Neighborsearching
cutoff-scheme = Verlet
ns_type = grid
nstlist = 10
rcoulomb = 1.0
rvdw = 1.0

; Electrostatics
coulombtype = PME
pme_order = 4
fourierspacing = 0.16

; Temperature coupling
tcoupl = V-rescale
tc-grps = Protein Non-Protein
tau_t = 0.1 0.1
ref_t = ${temp} ${temp}

; Pressure coupling
pcoupl = Parrinello-Rahman
pcoupltype = isotropic
tau_p = 2.0
ref_p = ${env.pressure || 1.0}
compressibility = 4.5e-5

; PBC
pbc = xyz

; Dispersion correction
DispCorr = EnerPres

; Velocity generation
gen_vel = no`;

  return [{
    filename: 'gromacs.mdp',
    content: mdp,
    description: `GROMACS MDP file — ${ff}, ${temp}K, ${time}. Run: gmx grompp -f gromacs.mdp -o topol.tpr`
  }];
}

function genVASP(inputs, env) {
  const functional = inputs.functional || 'PBE';
  const kpoints = inputs.kpoints || '4x4x4';
  const property = inputs.property || 'Band gap';
  const material = inputs.material || 'Si';

  const encut = functional.includes('HSE') ? 520 : 450;
  const isHSE = functional.includes('HSE');
  const isOpt = property.toLowerCase().includes('optim') || property.toLowerCase().includes('formation');

  const incar = `# VASP INCAR — generated by Suttain
# Material: ${material}
# Functional: ${functional}
# Property: ${property}

SYSTEM = ${material}
PREC = Accurate
ENCUT = ${encut}
EDIFF = 1E-6
EDIFFG = -0.01
${isOpt ? 'IBRION = 2\nNSW = 100\nISIF = 3' : 'IBRION = -1\nNSW = 0'}
ISMEAR = 0
SIGMA = 0.05
LREAL = Auto
LWAVE = .FALSE.
LCHARG = .TRUE.
${isHSE ? 'LHFCALC = .TRUE.\nGGA = PE\nHFSCREEN = 0.2\nALGO = Damped\nTIME = 0.4' : '# GGA = PE'}
${property.includes('DOS') || property.includes('Band') ? 'LORBIT = 11\nICHARG = 2' : ''}
${property.includes('Band structure') ? 'ICHARG = 11' : ''}
${property.includes('Phonon') ? 'IBRION = 6\nNFREE = 2\nPOTIM = 0.015\nNSW = 1' : ''}
${property.includes('Magnetic') ? 'ISPIN = 2\nMAGMOM = 5*2.0' : ''}
${property.includes('Dielectric') ? 'LEPSILON = .TRUE.' : ''}`;

  const kpointsContent = `Automatic mesh
0
Gamma
${kpoints.split('x').join(' ')}
0 0 0`;

  return [
    { filename: 'INCAR', content: incar, description: `VASP INCAR — ${functional}, ${property}` },
    { filename: 'KPOINTS', content: kpointsContent, description: `K-point mesh: ${kpoints}` },
  ];
}

function genQuantumESPRESSO(inputs, env) {
  const functional = inputs.functional || 'PBE';
  const kpoints = inputs.kpoints || '4 4 4';
  const material = inputs.material || 'Si';
  const property = inputs.property || 'Band gap';

  const content = `&CONTROL
  calculation = '${property.includes('optim') ? 'relax' : 'scf'}'
  prefix = '${material.replace(/[^a-zA-Z]/g, '')}'
  pseudo_dir = './pseudo/'
  outdir = './out/'
  verbosity = 'high'
  tstress = .true.
  tprnfor = .true.
/

&SYSTEM
  ibrav = 0
  nat = 2
  ntyp = 1
  ecutwfc = 40.0
  ecutrho = 320.0
  occupations = 'smearing'
  smearing = 'gaussian'
  degauss = 0.02
${functional.includes('HSE') ? "  input_dft = 'HSE'\n  nqx1 = 4, nqx2 = 4, nqx3 = 4" : "  nspin = 1"}
/

&ELECTRONS
  conv_thr = 1.0D-8
  mixing_beta = 0.7
  electron_maxstep = 100
/

&IONS
  ion_dynamics = 'bfgs'
/

&CELL
  cell_dynamics = 'bfgs'
  press_conv_thr = 0.1
/

ATOMIC_SPECIES
Si 28.0855 Si.pbe-rrkj.UPF

CELL_PARAMETERS angstrom
0.0 2.715 2.715
2.715 0.0 2.715
2.715 2.715 0.0

ATOMIC_POSITIONS crystal
Si 0.00 0.00 0.00
Si 0.25 0.25 0.25

K_POINTS automatic
${kpoints} 0 0 0`;

  return [{
    filename: 'qe_input.in',
    content,
    description: `Quantum ESPRESSO input — ${functional}, ${property}. Run: pw.x < qe_input.in > qe_output.out`
  }];
}

function genLAMMPS(inputs, env) {
  const temp = inputs.temperature || env.temperature || 300;
  const system = inputs.system || 'Material system';

  const content = `# LAMMPS input — generated by Suttain
# System: ${system}
# Temperature: ${temp} K

units metal
atom_style atomic
boundary p p p

# Read structure
read_data structure.data

# Interatomic potential
pair_style eam/alloy
pair_coeff * * potential.eam.alloy

# Neighbor list
neighbor 2.0 bin
neigh_modify delay 5

# Minimization
min_style cg
minimize 1e-6 1e-8 1000 10000

# Reset timestep
reset_timestep 0

# Thermodynamic output
thermo 100
thermo_style custom step temp pe ke etotal press vol

# Temperature initialization
velocity all create ${temp} 12345 mom yes rot no dist gaussian

# NPT ensemble
fix 1 all npt temp ${temp} ${temp} 0.1 iso 1.0 1.0 1.0

# Output trajectory
dump 1 all custom 1000 trajectory.lammpstrj id type x y z

# Run
timestep 0.001
run 100000`;

  return [{
    filename: 'lammps.in',
    content,
    description: `LAMMPS input — NPT MD at ${temp}K. Run: lmp -in lammps.in`
  }];
}

function genAutoDockVina(inputs, env) {
  const ligand = inputs.ligand || 'ligand';
  const receptor = inputs.receptor || 'receptor';

  const content = `# AutoDock Vina config — generated by Suttain
# Receptor: ${receptor}
# Ligand: ${ligand}

receptor = receptor.pdbqt
ligand = ligand.pdbqt

# Grid box (center on binding site)
center_x = 0.0
center_y = 0.0
center_z = 0.0

size_x = 20.0
size_y = 20.0
size_z = 20.0

# Search parameters
exhaustiveness = 8
num_modes = 10
energy_range = 3

# Output
out = vina_results.pdbqt
log = vina.log`;

  return [{
    filename: 'vina_config.txt',
    content,
    description: `AutoDock Vina config. Run: vina --config vina_config.txt`
  }];
}

function genOpenMM(inputs, env) {
  const ff = inputs.force_field || env.forcefield || 'AMBER14SB';
  const temp = inputs.temperature || env.temperature || 300;
  const time = inputs.simulation_time || '100 ns';
  const system = inputs.system || 'Protein in water';

  const content = `# OpenMM Python script — generated by Suttain
# System: ${system}
# Force field: ${ff}
# Temperature: ${temp} K, ${time}

from openmm.app import *
from openmm import *
from simtk.openmm import XmlSerializer
import simtk.unit as unit

# Load PDB
pdb = PDBFile('system.pdb')

# Force field
forcefield = ForceField('${ff}.xml', '${ff}_water.xml')

# System with periodic boundary conditions
system = forcefield.createSystem(pdb.topology,
    nonbondedMethod=PME,
    nonbondedCutoff=1.0*unit.nanometer,
    constraints=HBonds)

# Integrator
integrator = LangevinIntegrator(${temp}*unit.kelvin,
    1.0/unit.picosecond,
    0.002*unit.picoseconds)

# Platform
platform = Platform.getPlatformByName('CUDA')
simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)

# Minimize
print('Minimizing...')
simulation.minimizeEnergy(maxIterations=1000)

# Equilibrate
simulation.reporters.append(StateDataReporter(stdout, 1000,
    step=True, potentialEnergy=True, temperature=True, volume=True))
simulation.reporters.append(DCDReporter('trajectory.dcd', 5000))

# Production run
print('Running production...')
nsteps = ${time.includes('ns') ? parseInt(time) * 500000 : 50000000}
simulation.step(nsteps)

# Save final state
state = simulation.context.getState(getPositions=True)
with open('final_state.xml', 'w') as f:
    f.write(XmlSerializer.serialize(state))`;

  return [{
    filename: 'openmm_run.py',
    content,
    description: `OpenMM Python script — ${ff}, ${temp}K, GPU-accelerated. Run: python openmm_run.py`
  }];
}

function genNWCHEM(inputs, env) {
  const functional = inputs.functional || 'B3LYP';
  const basis = inputs.basis_set || '6-31G*';
  const task = inputs.task || 'geometry optimization';
  const molecule = inputs.molecule || 'H2O';

  const content = `NWChem input — generated by Suttain
# Molecule: ${molecule}
# Method: ${functional}/${basis}
# Task: ${task}

start molecule

geometry units angstrom
  O  0.000  0.000  0.000
  H  0.000  0.000  0.957
  H  0.000  0.957  0.000
end

basis
  * library ${basis}
end

dft
  xc ${functional.toLowerCase().replace('-', ' ')}
  mult 1
end

task dft ${task.includes('optim') ? 'optimize' : 'energy'}`;

  return [{
    filename: 'nwchem.nw',
    content,
    description: `NWChem input — ${functional}/${basis}. Run: nwchem nwchem.nw`
  }];
}

function genCP2K(inputs, env) {
  const functional = inputs.functional || 'PBE';
  const temp = inputs.temperature || env.temperature || 300;
  const system = inputs.system || 'Material system';

  const content = `&GLOBAL
  PROJECT ${system.replace(/\s/g, '_')}
  RUN_TYPE ENERGY
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD Quickstep
  &DFT
    BASIS_SET_FILE_NAME BASIS_MOLOPT
    POTENTIAL_FILE_NAME POTENTIAL
    &MGRID
      CUTOFF 400
      REL_CUTOFF 50
    &END MGRID
    &QS
      EPS_DEFAULT 1.0E-10
    &END QS
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF 1.0E-6
      MAX_SCF 50
    &END SCF
    &XC
      &XC_FUNCTIONAL ${functional}
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &SUBSYS
    &CELL
      ABC 10.0 10.0 10.0
      PERIODIC XYZ
    &END CELL
    &COORD
      O 0.0 0.0 0.0
      H 0.0 0.0 1.0
      H 0.0 1.0 0.0
    &END COORD
  &END SUBSYS
&END FORCE_EVAL`;

  return [{
    filename: 'cp2k.inp',
    content,
    description: `CP2K input — ${functional}. Run: cp2k.popt -i cp2k.inp`
  }];
}

function generateInputFiles(simType, engine, inputs, env) {
  const e = (engine || '').toLowerCase();

  if (e.includes('orca')) return genORCA(inputs, env);
  if (e.includes('gromacs')) return genGROMACS(inputs, env);
  if (e.includes('vasp')) return genVASP(inputs, env);
  if (e.includes('quantum espresso') || e.includes('espresso')) return genQuantumESPRESSO(inputs, env);
  if (e.includes('lammps')) return genLAMMPS(inputs, env);
  if (e.includes('autodock') || e.includes('vina')) return genAutoDockVina(inputs, env);
  if (e.includes('openmm')) return genOpenMM(inputs, env);
  if (e.includes('nwchem')) return genNWCHEM(inputs, env);
  if (e.includes('cp2k')) return genCP2K(inputs, env);

  // Fallback: generic
  return [{
    filename: 'input.txt',
    content: `# Generic simulation input — generated by Suttain
# Engine: ${engine}
# Simulation type: ${simType}
# Inputs: ${JSON.stringify(inputs, null, 2)}
# Environment: ${JSON.stringify(env, null, 2)}`,
    description: `Generic input file for ${engine}`
  }];
}

// ── Main handler ───────────────────────────────────────────────────

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { sim_type, engine, inputs, environmental_params } = body;

    if (!engine) return Response.json({ error: 'Engine is required' }, { status: 400 });

    const env = environmental_params || {};
    const files = generateInputFiles(sim_type, engine, inputs || {}, env);

    return Response.json({
      files,
      engine,
      sim_type,
      summary: `Generated ${files.length} input file${files.length !== 1 ? 's' : ''} for ${engine}`,
      method_note: 'Input files generated using Suttain simulation input generator (engine-specific templates)',
    });
  } catch (error) {
    console.error('generateSimulationInputs error:', error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});