import React,{useState} from 'react';
import { Button } from '@/components/ui/button';
import useEngineRegistry from '@/components/simulation/useEngineRegistry';
import ApiOperationList from '@/components/api/ApiOperationList';
const url='https://suttain.base44.app/functions/researchApi';
export default function ApiRequestDocs() {
 const [language,setLanguage]=useState('Python'),{data}=useEngineRegistry();
 const python=`import os, requests\n\nresponse = requests.post(\n    "${url}",\n    headers={"Authorization": "Bearer " + os.environ["SUTTAIN_API_KEY"]},\n    json={"operation": "comprehensiveChemicalSearch",\n          "input": {"query": "aspirin", "database": "PubChem"}},\n    timeout=90,\n)\nresponse.raise_for_status()\nprint(response.json())`;
 const curl=`curl '${url}' \\\n  -H "Authorization: Bearer $SUTTAIN_API_KEY" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"operation":"comprehensiveChemicalSearch","input":{"query":"aspirin","database":"PubChem"}}'`;
 return <section id="api-requests" className="scroll-mt-24 mb-10 space-y-5"><h2>Scripts and notebooks</h2><p className="text-sm text-muted-foreground">Use POST with <code>Authorization: Bearer &lt;your key&gt;</code>. Send a JSON object containing <code>operation</code> and <code>input</code>. No Base44 account token is needed in your script.</p><code className="block break-all rounded-lg bg-muted p-4 text-sm">POST {url}</code><div className="flex gap-2">{['Python','cURL'].map(name=><Button key={name} size="sm" variant={language===name?'secondary':'ghost'} aria-pressed={language===name} onClick={()=>setLanguage(name)}>{name}</Button>)}</div><pre className="rounded-lg bg-muted p-4 overflow-x-auto text-xs leading-relaxed">{language==='Python'?python:curl}</pre><p className="text-sm text-muted-foreground">Install Python’s <code>requests</code> package if needed. Set <code>SUTTAIN_API_KEY</code> in your environment or notebook secrets manager, never in notebook source.</p>
 <div className="rounded-lg border border-border p-5 space-y-3 text-sm"><h3 className="text-base">Limits, responses, and security</h3><p className="text-muted-foreground">Each key can be limited to 1–60 requests per UTC minute and 1–10,000 requests per UTC calendar month. Up to 20 key records per subscriber; archive revoked keys to free space. These are API request counts, not purchased compute credits. Existing provider and operation-specific limits also apply.</p><ul className="list-disc pl-5 text-muted-foreground space-y-1"><li>401: missing, invalid, or revoked key.</li><li>403: Research subscription inactive or resource access refused.</li><li>429: usage limit reached; wait for <code>Retry-After</code> seconds or adjust key limits.</li><li>400 / 413: invalid operation, input, or request larger than 32 KB.</li><li>5xx: operation or payment verification unavailable.</li></ul><p className="text-muted-foreground">Responses preserve the underlying operation’s JSON. Headers include <code>X-Request-Id</code>, <code>X-RateLimit-Remaining</code>, <code>X-MonthlyLimit-Remaining</code>, and <code>X-MonthlyLimit-Reset</code>. Admitted requests count even if the provider fails. Limit-denied requests never execute the operation.</p><p className="text-muted-foreground">Keys are stored as hashes and cannot be recovered. To rotate, create a replacement, update your scripts, then revoke the old key. Revocation or loss of subscription access blocks new requests; already-running calculations are not canceled.</p></div>
 <ApiOperationList engines={data?.engines || []}/></section>;
}