import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, CheckCircle2, AlertTriangle, XCircle, AlertCircle, FileDown, ShieldCheck, Globe, FlaskConical, ChevronDown, ChevronUp, Lightbulb, Info, Package, TrendingUp, Clock, Zap } from 'lucide-react';
import { format } from 'date-fns';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const statusConfig = {
  Compliant: { 
    bg: 'bg-emerald-50', 
    border: 'border-emerald-200',
    badge: 'bg-emerald-500 text-white',
    icon: CheckCircle2,
    iconColor: 'text-emerald-500',
    label: 'Compliant'
  },
  Restricted: { 
    bg: 'bg-amber-50', 
    border: 'border-amber-200',
    badge: 'bg-amber-500 text-white',
    icon: AlertTriangle,
    iconColor: 'text-amber-500',
    label: 'Restricted'
  },
  Banned: { 
    bg: 'bg-red-50', 
    border: 'border-red-200',
    badge: 'bg-red-500 text-white',
    icon: XCircle,
    iconColor: 'text-red-500',
    label: 'Banned'
  },
  'Requires Warning': { 
    bg: 'bg-yellow-50', 
    border: 'border-yellow-200',
    badge: 'bg-yellow-500 text-white',
    icon: AlertCircle,
    iconColor: 'text-yellow-500',
    label: 'Warning Required'
  },
  Unknown: { 
    bg: 'bg-slate-50', 
    border: 'border-slate-200',
    badge: 'bg-slate-500 text-white',
    icon: Info,
    iconColor: 'text-slate-500',
    label: 'Pending Review'
  },
};

const ComplianceResultDisplay = ({ result, onBack, productName }) => {
  const [expandedItems, setExpandedItems] = useState({});

  const toggleExpand = (index) => {
    setExpandedItems(prev => ({ ...prev, [index]: !prev[index] }));
  };

  // Calculate compliance stats
  const stats = {
    total: result.compliance_details?.length || 0,
    compliant: result.compliance_details?.filter(d => d.status === 'Compliant').length || 0,
    restricted: result.compliance_details?.filter(d => d.status === 'Restricted').length || 0,
    banned: result.compliance_details?.filter(d => d.status === 'Banned').length || 0,
    warning: result.compliance_details?.filter(d => d.status === 'Requires Warning').length || 0,
  };
  const complianceScore = stats.total > 0 ? Math.round((stats.compliant / stats.total) * 100) : 0;

  const handleDownloadReport = () => {
    const reportContent = `
REGULATORY COMPLIANCE REPORT
============================
Product: ${productName}
Date: ${format(new Date(), 'MMMM dd, yyyy')}
Regions Checked: ${result.checked_regions?.join(', ') || 'N/A'}
Compliance Score: ${complianceScore}%

EXECUTIVE SUMMARY
-----------------
${result.summary}

COMPLIANCE STATISTICS
---------------------
Total Ingredients: ${stats.total}
Compliant: ${stats.compliant}
Restricted: ${stats.restricted}
Banned: ${stats.banned}
Requires Warning: ${stats.warning}

DETAILED INGREDIENT ANALYSIS
----------------------------
${result.compliance_details?.map((detail, idx) => `
${idx + 1}. ${detail.ingredient}
   Status: ${detail.status}
   Details: ${detail.details}
   Recommendation: ${detail.recommendation}
`).join('\n') || 'No details available'}

${result.predictive_insights ? `
PREDICTIVE INSIGHTS & FUTURE TRENDS
-----------------------------------
Emerging Regulatory Trends:
${result.predictive_insights.emerging_trends?.map((trend, idx) => `${idx + 1}. ${trend}`).join('\n') || 'None identified'}

Potential Future Restrictions:
${result.predictive_insights.potential_restrictions?.map((res, idx) => `
${idx + 1}. ${res.ingredient}
   Risk Level: ${res.risk_level}
   Expected Timeline: ${res.timeline}
   Rationale: ${res.rationale}
`).join('\n') || 'None identified'}

Proactive Recommendations:
${result.predictive_insights.proactive_recommendations?.map((rec, idx) => `${idx + 1}. ${rec}`).join('\n') || 'None provided'}
` : ''}

---
Report generated by Suttain AI Compliance Co-Pilot
${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${productName.replace(/\s+/g, '-').toLowerCase()}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-6">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
          <Button variant="ghost" onClick={onBack} className="self-start hover:bg-slate-100">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Dashboard
          </Button>
          <Button onClick={handleDownloadReport} className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white shadow-lg">
            <FileDown className="w-4 h-4 mr-2"/> Export Report
          </Button>
        </div>

        {/* Product Header Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-6"
        >
          <Card className="border-0 shadow-xl overflow-hidden">
            <div className="bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600 p-6 text-white">
              <div className="flex items-start gap-4">
                <div className="w-14 h-14 bg-white/20 backdrop-blur-sm rounded-xl flex items-center justify-center flex-shrink-0">
                  <Package className="w-7 h-7 text-white" />
                </div>
                <div className="flex-1">
                  <h1 className="text-2xl font-bold mb-1">{productName}</h1>
                  <div className="flex flex-wrap items-center gap-3 text-white/90 text-sm">
                    <span className="flex items-center gap-1.5">
                      <Globe className="w-4 h-4" />
                      {result.checked_regions?.length || 0} Regions
                    </span>
                    <span className="flex items-center gap-1.5">
                      <FlaskConical className="w-4 h-4" />
                      {stats.total} Ingredients
                    </span>
                    <span className="flex items-center gap-1.5">
                      <ShieldCheck className="w-4 h-4" />
                      {format(new Date(), 'MMM dd, yyyy')}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        {/* Stats Overview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-6"
        >
          <Card className="border-0 shadow-lg col-span-2 lg:col-span-1">
            <CardContent className="p-4 text-center">
              <div className="relative w-20 h-20 mx-auto mb-2">
                <svg className="w-20 h-20 transform -rotate-90">
                  <circle cx="40" cy="40" r="36" stroke="#e2e8f0" strokeWidth="8" fill="none" />
                  <circle 
                    cx="40" cy="40" r="36" 
                    stroke={complianceScore >= 80 ? '#10b981' : complianceScore >= 50 ? '#f59e0b' : '#ef4444'}
                    strokeWidth="8" 
                    fill="none"
                    strokeDasharray={`${complianceScore * 2.26} 226`}
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="text-xl font-bold text-slate-900">{complianceScore}%</span>
                </div>
              </div>
              <p className="text-xs text-slate-600 font-medium">Compliance Score</p>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-emerald-50">
            <CardContent className="p-4 text-center">
              <CheckCircle2 className="w-8 h-8 text-emerald-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-emerald-700">{stats.compliant}</p>
              <p className="text-xs text-emerald-600 font-medium">Compliant</p>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-amber-50">
            <CardContent className="p-4 text-center">
              <AlertTriangle className="w-8 h-8 text-amber-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-amber-700">{stats.restricted}</p>
              <p className="text-xs text-amber-600 font-medium">Restricted</p>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-red-50">
            <CardContent className="p-4 text-center">
              <XCircle className="w-8 h-8 text-red-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-red-700">{stats.banned}</p>
              <p className="text-xs text-red-600 font-medium">Banned</p>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-yellow-50">
            <CardContent className="p-4 text-center">
              <AlertCircle className="w-8 h-8 text-yellow-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-yellow-700">{stats.warning}</p>
              <p className="text-xs text-yellow-600 font-medium">Warning</p>
            </CardContent>
          </Card>
        </motion.div>

        {/* Executive Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mb-6"
        >
          <Card className="border-0 shadow-lg overflow-hidden">
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border-l-4 border-indigo-500 p-5">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <Lightbulb className="w-5 h-5 text-indigo-600" />
                </div>
                <div>
                  <h3 className="font-bold text-indigo-900 mb-2">Analysis Overview</h3>
                  <p className="text-sm text-indigo-800 leading-relaxed">{result.summary}</p>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        {/* Regions Checked */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35 }}
          className="mb-6"
        >
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium text-slate-600 mr-2">Regions Analyzed:</span>
            {result.checked_regions?.map((region, idx) => (
              <Badge key={idx} variant="outline" className="bg-white border-slate-300 text-slate-700">
                <Globe className="w-3 h-3 mr-1" />
                {region}
              </Badge>
            ))}
          </div>
        </motion.div>

        {/* Tabs for Different Sections */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Tabs defaultValue="ingredients" className="space-y-4">
            <TabsList className="grid w-full grid-cols-2 bg-white shadow-md">
              <TabsTrigger value="ingredients">
                <FlaskConical className="w-4 h-4 mr-2" />
                Ingredients
              </TabsTrigger>
              <TabsTrigger value="predictive">
                <TrendingUp className="w-4 h-4 mr-2" />
                Future Insights
              </TabsTrigger>
            </TabsList>

            {/* Ingredient Analysis Tab */}
            <TabsContent value="ingredients">
              <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <FlaskConical className="w-5 h-5 text-purple-600" />
                Ingredient Analysis
              </h2>
          
          <div className="space-y-3">
            {result.compliance_details?.map((item, index) => {
              const config = statusConfig[item.status] || statusConfig.Unknown;
              const StatusIcon = config.icon;
              const isExpanded = expandedItems[index];

              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 * index }}
                >
                  <Card className={`border-0 shadow-md overflow-hidden transition-all duration-300 hover:shadow-lg ${config.bg} ${config.border} border-l-4`}>
                    <div 
                      className="p-4 cursor-pointer"
                      onClick={() => toggleExpand(index)}
                    >
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          <div className={`w-10 h-10 rounded-full flex items-center justify-center bg-white shadow-sm flex-shrink-0`}>
                            <StatusIcon className={`w-5 h-5 ${config.iconColor}`} />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h4 className="font-bold text-slate-900 truncate">{item.ingredient}</h4>
                            <div className="flex items-center gap-2 mt-1">
                              <Badge className={`${config.badge} text-xs font-semibold`}>
                                {config.label}
                              </Badge>
                            </div>
                          </div>
                        </div>
                        <Button variant="ghost" size="sm" className="flex-shrink-0 ml-2">
                          {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                        </Button>
                      </div>
                    </div>

                    <AnimatePresence>
                      {isExpanded && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.2 }}
                          className="overflow-hidden"
                        >
                          <div className="px-4 pb-4 pt-0">
                            <div className="bg-white/80 rounded-xl p-4 space-y-4">
                              <div>
                                <h5 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Regulatory Details</h5>
                                <p className="text-sm text-slate-700 leading-relaxed">{item.details}</p>
                              </div>
                              
                              {item.recommendation && (
                                <div className="pt-3 border-t border-slate-200">
                                  <h5 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                                    <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
                                    Recommendation
                                  </h5>
                                  <p className="text-sm text-slate-700 leading-relaxed">{item.recommendation}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </Card>
                </motion.div>
              );
              })}
              </div>
              </TabsContent>

              {/* Predictive Insights Tab */}
              <TabsContent value="predictive">
              {result.predictive_insights ? (
                <div className="space-y-6">
                  <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                    <TrendingUp className="w-5 h-5 text-purple-600" />
                    Predictive Analysis & Future Trends
                  </h2>

                  {/* Emerging Trends */}
                  {result.predictive_insights.emerging_trends && result.predictive_insights.emerging_trends.length > 0 && (
                    <Card className="border-0 shadow-lg bg-gradient-to-br from-blue-50 to-cyan-50 border-l-4 border-blue-500">
                      <CardContent className="p-6">
                        <div className="flex items-center gap-3 mb-4">
                          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center">
                            <Zap className="w-5 h-5 text-white" />
                          </div>
                          <h3 className="font-bold text-slate-900 text-lg">Emerging Regulatory Trends</h3>
                        </div>
                        <ul className="space-y-3">
                          {result.predictive_insights.emerging_trends.map((trend, index) => (
                            <motion.li
                              key={index}
                              initial={{ opacity: 0, x: -20 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: 0.05 * index }}
                              className="flex items-start gap-3 p-3 bg-white/80 rounded-lg"
                            >
                              <TrendingUp className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                              <p className="text-sm text-slate-700 leading-relaxed">{trend}</p>
                            </motion.li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                  )}

                  {/* Potential Restrictions */}
                  {result.predictive_insights.potential_restrictions && result.predictive_insights.potential_restrictions.length > 0 && (
                    <Card className="border-0 shadow-lg bg-gradient-to-br from-amber-50 to-orange-50 border-l-4 border-amber-500">
                      <CardContent className="p-6">
                        <div className="flex items-center gap-3 mb-4">
                          <div className="w-10 h-10 bg-amber-600 rounded-xl flex items-center justify-center">
                            <Clock className="w-5 h-5 text-white" />
                          </div>
                          <h3 className="font-bold text-slate-900 text-lg">Potential Future Restrictions</h3>
                        </div>
                        <div className="space-y-4">
                          {result.predictive_insights.potential_restrictions.map((restriction, index) => (
                            <motion.div
                              key={index}
                              initial={{ opacity: 0, y: 10 }}
                              animate={{ opacity: 1, y: 0 }}
                              transition={{ delay: 0.05 * index }}
                              className="p-4 bg-white rounded-xl border-2 border-amber-200"
                            >
                              <div className="flex items-start justify-between mb-3">
                                <div>
                                  <h4 className="font-bold text-slate-900 mb-1">{restriction.ingredient}</h4>
                                  <div className="flex items-center gap-2">
                                    <Badge className={`${
                                      restriction.risk_level === 'High' ? 'bg-red-500' :
                                      restriction.risk_level === 'Medium' ? 'bg-amber-500' :
                                      'bg-yellow-500'
                                    } text-white`}>
                                      {restriction.risk_level} Risk
                                    </Badge>
                                    <Badge variant="outline" className="text-slate-600">
                                      <Clock className="w-3 h-3 mr-1" />
                                      {restriction.timeline}
                                    </Badge>
                                  </div>
                                </div>
                              </div>
                              <p className="text-sm text-slate-700 leading-relaxed">{restriction.rationale}</p>
                            </motion.div>
                          ))}
                        </div>
                      </CardContent>
                    </Card>
                  )}

                  {/* Proactive Recommendations */}
                  {result.predictive_insights.proactive_recommendations && result.predictive_insights.proactive_recommendations.length > 0 && (
                    <Card className="border-0 shadow-lg bg-gradient-to-br from-green-50 to-emerald-50 border-l-4 border-green-500">
                      <CardContent className="p-6">
                        <div className="flex items-center gap-3 mb-4">
                          <div className="w-10 h-10 bg-green-600 rounded-xl flex items-center justify-center">
                            <Lightbulb className="w-5 h-5 text-white" />
                          </div>
                          <h3 className="font-bold text-slate-900 text-lg">Proactive Recommendations</h3>
                        </div>
                        <ul className="space-y-3">
                          {result.predictive_insights.proactive_recommendations.map((rec, index) => (
                            <motion.li
                              key={index}
                              initial={{ opacity: 0, x: -20 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: 0.05 * index }}
                              className="flex items-start gap-3 p-3 bg-white/80 rounded-lg"
                            >
                              <CheckCircle2 className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                              <p className="text-sm text-slate-700 leading-relaxed">{rec}</p>
                            </motion.li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                  )}
                </div>
              ) : (
                <div className="text-center py-12">
                  <TrendingUp className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                  <p className="text-slate-600">No predictive insights available for this analysis</p>
                </div>
              )}
              </TabsContent>
              </Tabs>
              </motion.div>

        {/* Bottom Action */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Button variant="outline" onClick={onBack} className="w-full sm:w-auto">
            <ArrowLeft className="w-4 h-4 mr-2" /> Start New Check
          </Button>
          <Button onClick={handleDownloadReport} className="w-full sm:w-auto bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white">
            <FileDown className="w-4 h-4 mr-2"/> Download Full Report
          </Button>
        </motion.div>
      </motion.div>
    </div>
  );
};

export default ComplianceResultDisplay;