import mdEngineRegistry from './mdEngineRegistry.ts';
import maceEngineRegistry from './maceEngineRegistry.ts';
import {rowanMethods,rowanTasks} from './rowanCapabilities.ts';
const molecular = ['dft','quantum_mechanics'];
const periodic = ['materials','surface_chemistry'];
const xyz = '3\nWater reference\nO 0 0 0\nH 0 0 0.9572\nH 0.9266 0 -0.2396';
const baseSchema = {type:'object',required:['sim_type','engine','inputs'],properties:{sim_type:{type:'string'},engine:{type:'string'},inputs:{type:'object',properties:{geometry_xyz:{type:'string',description:'XYZ coordinates in angstroms; maximum 120 atoms.'},engine_method:{type:'string'},engine_task:{type:'string'},charge:{type:'integer',minimum:-10,maximum:10},multiplicity:{type:'integer',minimum:1,maximum:7},basis_set:{type:'string'},cell:{type:'string',description:'Nine Cartesian lattice-vector components in angstroms.'},pseudopotentials:{type:'string',description:'JSON mapping element symbols to local pseudopotential filenames.'}}},environmental_params:{type:'object'},record_job:{type:'boolean',default:true}}};
function local(id,label,methods,tasks,types,url,license,citation,extra={}) {
  const endpoints={psi4:'generatePsi4Inputs',pyscf:'generatePyscfInputs',nwchem:'generateNwchemInputs',cp2k:'generateCp2kInputs',espresso:'generateEspressoInputs',abinit:'generateAbinitInputs',siesta:'generateSiestaInputs',gpaw:'generateGpawInputs',octopus:'generateOctopusInputs',openmolcas:'generateOpenmolcasInputs',bagel:'generateBagelInputs',gamess:'generateGamessInputs',orca:'generateOrcaInputs',xtb:'generateXtbInputs',rdkit:'generateRdkitInputs'};
  return {id,label,deployment:'input_file',availability:'local',sim_types:types,methods,tasks,version:'Reported by your installed executable; no engine runs during preparation.',docs_url:url,license,citation,endpoint:endpoints[id],parameter_schema:baseSchema,example:{sim_type:types[0],engine:label,inputs:{geometry_xyz:xyz,engine_method:methods[0],engine_task:tasks[0],charge:0,multiplicity:1,basis_set:id==='gamess'?'6-31G*':'def2-SVP',...(extra.periodic ? {cell:'12 0 0 0 12 0 0 0 12'} : {}),...(extra.pseudo_required ? {pseudopotentials:JSON.stringify(id==='espresso'?{O:'O.pbe.UPF',H:'H.pbe.UPF'}:id==='siesta'?{O:'O.psf',H:'H.psf'}:{O:'08-O.PBE.fhi',H:'01-H.PBE.fhi'})} : {})},environmental_params:{solvent:'none'},record_job:false},...extra};
}
const energy = ['Single-point energy'], opt = [...energy,'Geometry optimization'], vib=[...opt,'Frequency analysis (IR/Raman)'];
export const engineRegistry = [
  ...mdEngineRegistry(),
  maceEngineRegistry(),
  {id:'rowan',label:'Rowan',deployment:'hosted',availability:'live',sim_types:molecular,methods:Object.keys(rowanMethods),tasks:Object.keys(rowanTasks),version:'Returned in provider calculation metadata',docs_url:'https://docs.rowansci.com/api',license:'Commercial hosted service; Rowan credits required.',citation:'Rowan Scientific. Cite Rowan and the actual calculation engine, method and basis set. https://docs.rowansci.com/citations',endpoint:'runRowanCompute',parameter_schema:{type:'object',required:['sim_type','inputs','structure'],properties:{sim_type:{enum:molecular},inputs:{type:'object'},structure:{type:'object'},auto_fallback:{type:'boolean',default:true}}},example:{sim_type:'dft',engine:'Rowan',inputs:{molecule:xyz,functional:'B3LYP',basis_set:'def2-SVP',task:'Single-point energy'},structure:{molecule:{charge:0,multiplicity:1,atoms:[{atomic_number:8,position:[0,0,0]},{atomic_number:1,position:[0,0,0.9572]},{atomic_number:1,position:[0.9266,0,-0.2396]}]}},environmental_params:{solvent:'none'},auto_fallback:true}},
  {id:'pubchem',label:'PubChem PUG-REST',deployment:'hosted',availability:'live',sim_types:['lookup'],methods:['Properties','Synonyms'],tasks:['Compound lookup'],version:'PUG-REST live database; timestamp and CID included',docs_url:'https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest',license:'Public data service; respect PubChem usage policy (maximum 5 requests/second).',citation:'Kim et al. An update on PUG-REST. Nucleic Acids Research 46 (2018) W563–W570. https://doi.org/10.1093/nar/gky294',endpoint:'runPubchemLookup',parameter_schema:{type:'object',required:['query'],properties:{query:{type:'string',maxLength:1000},namespace:{enum:['name','smiles','cid']},operation:{enum:['Properties','Synonyms']},sim_type:{type:'string'}}},example:{query:'aspirin',namespace:'name',operation:'Properties',sim_type:'dft'}},
  local('xtb','xtb',['GFN2-xTB','GFN1-xTB'],vib,molecular,'https://xtb-docs.readthedocs.io/en/latest/','LGPL-3.0; installed xtb binary required.','Bannwarth, Ehlert and Grimme. GFN2-xTB. J. Chem. Theory Comput. 15 (2019) 1652–1671. https://doi.org/10.1021/acs.jctc.8b01176',{hosting_note:'Live execution requires an external xtb worker; currently downloadable execution only.'}),
  local('rdkit','RDKit',['Descriptors','Morgan fingerprint','ETKDG conformer'],['Cheminformatics'],['cheminformatics'],'https://www.rdkit.org/docs/','BSD-3-Clause; local Python RDKit installation required.','RDKit: Open-source cheminformatics. https://www.rdkit.org/ Cite the installed RDKit release.',{hosting_note:'Live execution requires an external Python/RDKit worker; currently downloadable execution only.',example:{sim_type:'cheminformatics',engine:'RDKit',inputs:{smiles:'CCO',engine_method:'Descriptors',engine_task:'Cheminformatics'},record_job:false}}),
  local('psi4','Psi4',['HF','B3LYP','PBE','PBE0','MP2','CCSD','CCSD(T)'],vib,molecular,'https://psicode.org/psi4manual/master/','LGPL-3.0.','Smith et al. Psi4 1.4. J. Chem. Phys. 152 (2020) 184108. https://doi.org/10.1063/5.0006002'),
  local('pyscf','PySCF',['HF','B3LYP','PBE','PBE0','MP2','CCSD','CCSD(T)'],energy,molecular,'https://pyscf.org/','Apache-2.0.','Sun et al. Recent developments in the PySCF program package. J. Chem. Phys. 153 (2020) 024109. https://doi.org/10.1063/5.0006074'),
  local('nwchem','NWChem',['HF','B3LYP','PBE','PBE0','MP2'],vib,molecular,'https://nwchemgit.github.io/','Educational Community License 2.0.','Aprà et al. NWChem: Past, present, and future. J. Chem. Phys. 152 (2020) 184102. https://doi.org/10.1063/5.0004997'),
  local('cp2k','CP2K',['PBE'],opt,[...molecular,...periodic],'https://manual.cp2k.org/','GPL-2.0; CP2K basis/potential data files required.','Kühne et al. CP2K: An electronic structure and molecular dynamics software package. J. Chem. Phys. 152 (2020) 194103. https://doi.org/10.1063/5.0007045',{periodic:true}),
  local('espresso','Quantum ESPRESSO',['PBE','LDA'],opt,periodic,'https://www.quantum-espresso.org/Doc/INPUT_PW.html','GPL-2.0; locally installed ASE, pw.x and matching UPF pseudopotentials required.','Giannozzi et al. Advanced capabilities for materials modelling with Quantum ESPRESSO. J. Phys.: Condens. Matter 29 (2017) 465901. https://doi.org/10.1088/1361-648X/aa8f79',{periodic:true,pseudo_required:true}),
  local('abinit','ABINIT',['PBE','LDA'],opt,periodic,'https://docs.abinit.org/','GPL; ASE, ABINIT and matching pseudopotentials required.','Gonze et al. The ABINIT project. Comput. Phys. Commun. 248 (2020) 107042. https://doi.org/10.1016/j.cpc.2019.107042',{periodic:true,pseudo_required:true}),
  local('siesta','SIESTA',['PBE','LDA'],opt,periodic,'https://docs.siesta-project.org/','GPL; ASE and matching SIESTA pseudopotentials required.','Soler et al. The SIESTA method for ab initio order-N materials simulation. J. Phys.: Condens. Matter 14 (2002) 2745. https://doi.org/10.1088/0953-8984/14/11/302',{periodic:true,pseudo_required:true}),
  local('gpaw','GPAW',['PBE','LDA'],opt,periodic,'https://gpaw.readthedocs.io/','GPL; ASE, GPAW and PAW dataset installation required.','Enkovaara et al. Electronic structure calculations with GPAW. J. Phys.: Condens. Matter 22 (2010) 253202. https://doi.org/10.1088/0953-8984/22/25/253202',{periodic:true}),
  local('octopus','Octopus',['LDA'],energy,periodic,'https://octopus-code.org/documentation/','GPL; ASE/Octopus and appropriate pseudopotentials required.','Tancogne-Dejean et al. Octopus. J. Chem. Phys. 152 (2020) 124119. https://doi.org/10.1063/1.5142502',{periodic:true}),
  local('openmolcas','OpenMolcas',['HF','CASSCF'],energy,molecular,'https://molcas.gitlab.io/OpenMolcas/','LGPL-2.1.','Fdez. Galván et al. OpenMolcas. J. Chem. Theory Comput. 15 (2019) 5925–5964. https://doi.org/10.1021/acs.jctc.9b00532',{active_space:true}),
  local('bagel','BAGEL',['HF','CASSCF'],energy,molecular,'https://nubakery.org/','GPL-3.0.','Shiozaki. BAGEL. WIREs Comput. Mol. Sci. 8 (2018) e1331. https://doi.org/10.1002/wcms.1331',{active_space:true}),
  local('gamess','GAMESS',['HF','B3LYP','MP2'],opt,molecular,'https://www.msg.chem.iastate.edu/gamess/','GAMESS distribution terms apply; registration and installation required.','Schmidt et al. General atomic and molecular electronic structure system. J. Comput. Chem. 14 (1993) 1347–1363. https://doi.org/10.1002/jcc.540141112'),
  local('orca','ORCA',['HF','B3LYP','PBE','PBE0','M06-2X','M06-L','CAM-B3LYP','BP86','TPSSh','r2SCAN'],vib,molecular,'https://www.faccts.de/docs/orca/6.1/manual/','Academic/personal use subject to ORCA terms; commercial licensing may apply.','Neese. Software update: The ORCA program system—Version 5.0. WIREs Comput. Mol. Sci. 12 (2022) e1606. https://doi.org/10.1002/wcms.1606')
];
export function findEngine(value) { const key=String(value || '').toLowerCase(); return engineRegistry.find(e => e.id===key || e.label.toLowerCase()===key); }
export function pickFallback(data) {
  const method=data.inputs.engine_method || data.inputs.functional || data.inputs.method;
  const task=data.inputs.engine_task || data.inputs.task || (data.inputs.properties==='Dipole moment' ? 'Single-point energy' : data.inputs.properties);
  return engineRegistry.find(e => e.id === (method==='GFN2-xTB' ? 'xtb' : 'orca') && e.sim_types.includes(data.sim_type) && e.methods.includes(method) && e.tasks.includes(task));
}