import inputGeometry from './inputGeometry.ts';
import {elements,invalid} from './rowanInput.ts';
export default async function prepareMacePackage(engine,data) {
  const i=data.inputs || {};
  const method=i.engine_method || engine.methods[0],task=i.engine_task || engine.tasks[0];
  if(!engine.methods.includes(method)||!engine.tasks.includes(task)) invalid('Select a listed MACE model and task.');
  if(Number(i.charge ?? 0)!==0 || Number(i.multiplicity ?? 1)!==1) invalid('These MACE templates do not support charge or spin controls. Use a neutral system within the selected model training domain.');
  const raw=String(i.geometry_xyz || i.molecule || i.compound || i.system || i.material || i.surface || '').trim();
  let g;
  if(/^\d+\s*\n/.test(raw)) {
    const lines=raw.split(/\r?\n/),count=Number(lines[0]);
    if(raw.length>24000 || count<1 || count>120 || lines.length<count+2) invalid('Supply valid XYZ coordinates for 1–120 atoms.');
    const atoms=lines.slice(2,count+2).map(line=>{const [symbol,...xyz]=line.trim().split(/\s+/);const position=xyz.map(Number);if(!elements.includes(symbol)||symbol==='X'||position.length!==3||position.some(v=>!Number.isFinite(v)||Math.abs(v)>10000)) invalid('Invalid XYZ element or coordinates.');return {symbol,position};});
    g={atoms,charge:0};
  } else {const resolved=await inputGeometry({...i,molecule:raw});g={...resolved,atoms:resolved.atoms.map(a=>({...a,symbol:elements[a.atomic_number]}))};}
  if(g.charge!==0) invalid('Charged reference structures are not supported by these MACE templates.');
  if(method==='MACE-OFF23' && g.atoms.some(a=>!['H','C','N','O','F','P','S','Cl','Br','I'].includes(a.symbol))) invalid('MACE-OFF23 supports H, C, N, O, F, P, S, Cl, Br and I only.');
  const periodic=i.mace_periodic===true;
  if(['materials','surface_chemistry'].includes(data.sim_type) && !periodic) invalid('Enable periodic boundaries and supply cell vectors for a materials or surface workflow.');
  let cell=null;
  if(periodic){const v=String(i.cell || '').trim().split(/[\s,]+/).map(Number);if(v.length!==9||v.some(n=>!Number.isFinite(n)||Math.abs(n)>1000)) invalid('Supply nine finite cell-vector components in angstroms.');const det=v[0]*(v[4]*v[8]-v[5]*v[7])-v[1]*(v[3]*v[8]-v[5]*v[6])+v[2]*(v[3]*v[7]-v[4]*v[6]);if(Math.abs(det)<1e-6) invalid('Cell vectors must span a nonzero volume.');cell=[v.slice(0,3),v.slice(3,6),v.slice(6,9)];}
  const number=(key,fallback,min,max,integer=false)=>{const n=Number(i[key] ?? fallback);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n))) invalid(`Invalid ${key.replaceAll('_',' ')} (${min}–${max}).`);return n;};
  const device=i.mace_device || 'cpu',ensemble=i.mace_ensemble || 'NVT';
  if(!['cpu','cuda'].includes(device)||!['NVE','NVT'].includes(ensemble)) invalid('Choose CPU/CUDA and NVE/NVT.');
  const fmax=number('mace_fmax',0.05,0.0001,1),optSteps=number('mace_opt_steps',200,1,10000,true),steps=number('mace_steps',1000,1,1000000,true),dt=number('mace_timestep_fs',0.5,0.01,5),temperature=number('mace_temperature',300,1,5000);
  const xyz=`${g.atoms.length}\nSuttain input geometry; not a computed result\n${g.atoms.map(a=>`${a.symbol} ${a.position.join(' ')}`).join('\n')}\n`;
  const action=task==='Geometry optimization'?`optimizer = BFGS(atoms, trajectory='optimization.traj', logfile='optimization.log')\nconverged = optimizer.run(fmax=${fmax}, steps=${optSteps})\nresult['converged'] = bool(converged)\nresult['optimization_steps'] = optimizer.nsteps\n`:task==='Molecular dynamics'?`rng = np.random.default_rng(42)\nMaxwellBoltzmannDistribution(atoms, temperature_K=${temperature}, rng=rng)\ndynamics = ${ensemble==='NVT'?`Langevin(atoms, timestep=${dt} * units.fs, temperature_K=${temperature}, friction=0.01 / units.fs, rng=rng, trajectory='md.traj', logfile='md.log', loginterval=10)`:`VelocityVerlet(atoms, timestep=${dt} * units.fs, trajectory='md.traj', logfile='md.log', loginterval=10)`}\ndynamics.run(${steps})\nresult.update(ensemble=${JSON.stringify(ensemble)}, steps=${steps}, timestep_fs=${dt}, initial_temperature_K=${temperature}, final_temperature_K=float(atoms.get_temperature()), trajectory='md.traj')\n`:'';
  const script=`# Prepared by Suttain; executes locally, not on Suttain.\nimport json\nfrom importlib.metadata import version\nimport numpy as np\nfrom ase import units\nfrom ase.io import read, write\nfrom ase.optimize import BFGS\nfrom ase.md.langevin import Langevin\nfrom ase.md.verlet import VelocityVerlet\nfrom ase.md.velocitydistribution import MaxwellBoltzmannDistribution\nfrom mace.calculators import mace_mp, mace_off\n\natoms = read('geometry.xyz')\n${periodic?`atoms.set_cell(${JSON.stringify(cell)})\natoms.set_pbc(True)`:'atoms.set_pbc(False)'}\n# Explicit medium selects MP-0, not the newer default MPA-0.\natoms.calc = ${method==='MACE-MP-0'?'mace_mp':'mace_off'}(model='medium', device=${JSON.stringify(device)}, default_dtype='float64'${method==='MACE-MP-0'?', dispersion=False':''})\nunsupported = set(atoms.numbers) - set(atoms.calc.z_table.zs)\nif unsupported: raise ValueError(f'Model does not cover atomic numbers: {sorted(unsupported)}')\nresult = {'model': ${JSON.stringify(method)}, 'task': ${JSON.stringify(task)}, 'mace_torch_version': version('mace-torch'), 'ase_version': version('ase'), 'periodic': ${periodic?'True':'False'}, 'device': ${JSON.stringify(device)}}\n${action}result['energy_eV'] = float(atoms.get_potential_energy())\nresult['forces_eV_per_A'] = atoms.get_forces().tolist()\nresult['positions_A'] = atoms.get_positions().tolist()\nresult['cell_A'] = atoms.cell.tolist()\nwrite('final.extxyz', atoms)\nwith open('result.json', 'w') as handle: json.dump(result, handle, indent=2)\nprint(json.dumps(result, indent=2))\n${task==='Geometry optimization'?"if not converged: raise RuntimeError('Optimization did not converge; inspect optimization.log and result.json')\n":''}`;
  const readme=`# MACE local ASE workflow\n\nNo calculation was executed by Suttain.\nModel: ${method} (medium checkpoint)\nTask: ${task}\n\nCreate a Python virtual environment and install dependencies with: python -m pip install -r requirements.txt\nRun: python mace_run.py > output.log 2>&1 (or bash run.sh).\nCUDA requires a compatible GPU and PyTorch build; CPU is the default. Model weights download and cache on first execution; internet access is required then. Only use trusted official checkpoints.\n\nOutputs: result.json (energy in eV, forces in eV/angstrom), final.extxyz, and ${task==='Molecular dynamics'?'md.traj / md.log':task==='Geometry optimization'?'optimization.traj / optimization.log':'output.log'}. View trajectories with ASE. Optimization stops at ${fmax} eV/angstrom or ${optSteps} steps and reports convergence. MD supports NVE or NVT only; NVT friction is 0.01/fs and random seed is 42.\n\nML potential predictions are not fresh DFT results, safety assessments, or guaranteed accuracy outside the training domain. MP-0 is trained on materials; OFF23 covers neutral organic systems using H/C/N/O/F/P/S/Cl/Br/I. No basis set, implicit solvent, charge/spin model, pressure control, pH, ionic strength, or custom classical forcefield is applied. Include explicit solvent atoms yourself if needed. Periodic cell vectors are used as supplied; no vacuum, solvation or cell relaxation is invented. Review geometry, timestep and stability before production MD.\n\nLicense: ${engine.license}\nCitation: ${engine.citation}\nDocumentation: ${engine.docs_url}\nRecord the checkpoint, package versions, model license and settings for reproducibility.\n`;
  const files=[{filename:'mace_run.py',content:script,description:'ASE script using a MACE foundation model; runs locally.'},{filename:'geometry.xyz',content:xyz,description:'Supplied or reference coordinates in angstroms.'},{filename:'requirements.txt',content:'mace-torch>=0.3.6,<0.4\nase>=3.23,<4\nnumpy>=1.26,<3\n',description:'Install in a dedicated Python environment.'},{filename:'run.sh',content:'#!/usr/bin/env bash\nset -euo pipefail\npython mace_run.py > output.log 2>&1\n',description:'Local execution launcher.'},{filename:'README.md',content:readme,description:'Installation, units, model licensing, citations and limitations.'}];
  if(JSON.stringify(files).length>100000) invalid('Generated MACE package is too large.');
  return {files,engine:'MACE',engine_id:'mace',sim_type:data.sim_type,method,task,execution_mode:'local_pending',citations:[{title:'MACE',text:engine.citation,url:engine.docs_url}],summary:'MACE ASE input package prepared; awaiting local execution.',method_note:'Deterministic script preparation only. No model inference or hosted compute was performed.'};
}