import mdSettings from './mdSettings.ts';
import openmmMdTemplate from './openmmMdTemplate.ts';
import gromacsMdTemplate from './gromacsMdTemplate.ts';
import {invalid} from './rowanInput.ts';
export default function prepareMdPackage(engine,data) {
  if(data.sim_type!=='molecular_dynamics') invalid('These classical MD templates support molecular_dynamics only; no enhanced-sampling method is substituted.');
  const inputs=data.inputs || {}, env=data.environmental_params || {};
  if(inputs.engine_method && inputs.engine_method!=='Classical MD') invalid('Only Classical MD is implemented for this engine.');
  if(inputs.engine_task && inputs.engine_task!=='Molecular dynamics') invalid('Only standard molecular dynamics is implemented for this engine.');
  const s=mdSettings(engine,inputs,env);
  const packageData=engine.id==='openmm'?openmmMdTemplate(s):gromacsMdTemplate(s);
  packageData.files.unshift({filename:'input.pdb',content:s.pdb,description:'User-supplied MD coordinates and residue topology; not a generated geometry.'});
  packageData.files.push({filename:'run.sh',content:`#!/usr/bin/env bash\n#SBATCH --job-name=suttain-${engine.id}\n#SBATCH --ntasks=1\n#SBATCH --cpus-per-task=8\n#SBATCH --time=01:00:00\nset -euo pipefail\n# Activate your engine environment; adjust HPC resources/time before submission.\n${packageData.command}\n`,description:'Local / SLURM launcher. Configure your installation and HPC resources first.'});
  packageData.files.push({filename:'README.md',content:`# ${engine.label} molecular dynamics\n\nSuttain prepared files only; no simulation has executed.\nRun bash run.sh, or configure SLURM and run sbatch run.sh.\n\nEnsemble: ${s.npt?'NPT':'NVT'}\nTemperature target: ${s.temperature} K (${s.thermostat})\nPressure target: ${s.npt?s.pressure+' bar ('+s.barostat+')':'not applied: NVT, barostat none'}\nForcefield: ${s.forcefield}\nAttached native file: ${s.attachment || 'none'}\nSolvent: ${s.solvent==='none'?'no added solvent':'explicit TIP3P water'}\nProduction: ${s.steps} steps at ${s.timestep} fs\nCustom LJ/bond/angle/dihedral rows: ${Object.values(s.overrides).reduce((n,rows)=>n+rows.length,0)}\n\n${packageData.requirements}\n${s.attachment?'Download your private forcefield attachment using the simulation page and place it next to these scripts.':''}\n\nCustom units: epsilon and torsion k in kJ/mol; sigma and r0 in nm; bond k in kJ/mol/nm^2; angle k in kJ/mol/rad^2; theta0 and torsion phase in degrees. Bond and angle force constants follow E=0.5*k*(displacement)^2. Labels must match exact atom types, not arbitrary atom names. Overrides modify existing interactions, never invent missing topology, partial charges or parameterize ligands. Unmatched rows fail before production.\n\npH and ionic strength remain recorded context, not automatic protonation/salt preparation. Protonation and ion composition must be validated before running. Temperature and pressure are coupling targets, not guaranteed measured values; check equilibration and output fluctuations. Outputs are real local engine files only after you run the scripts. Hosted execution is not connected.\n\nCitation: ${engine.citation}\nOfficial documentation: ${engine.docs_url}\nCite your installed engine version and the specific forcefield publications.\n`,description:'Actual applied settings, custom units, local dependencies and execution limitations.'});
  if(JSON.stringify(packageData.files).length>100000) invalid('MD input package exceeds the size limit.');
  return {files:packageData.files,engine:engine.label,engine_id:engine.id,sim_type:data.sim_type,method:'Classical MD',task:'Molecular dynamics',execution_mode:'local_pending',environmental_params:{...env,temperature:s.temperature,pressure:s.pressure,forcefield:s.forcefield,thermostat:s.thermostat,barostat:s.barostat},applied_settings:{temperature_K:s.temperature,pressure_bar:s.npt?s.pressure:null,ensemble:s.npt?'NPT':'NVT',thermostat:s.thermostat,barostat:s.barostat,forcefield:s.forcefield,custom_parameters_applied:s.hasOverrides,steps:s.steps,timestep_fs:s.timestep},citations:[{title:engine.label,text:engine.citation,url:engine.docs_url}],summary:`${engine.label} ${s.npt?'NPT':'NVT'} package prepared at ${s.temperature} K${s.npt?' and '+s.pressure+' bar':''}; forcefield and custom parameters are wired into local execution. No simulation has run.`,method_note:'Deterministic MD preparation with real thermostat/barostat controls and validated forcefield override tables.'};
}