import React, { useState } from 'react';
import { Copy, Check, Download, Plus, Trash2, ChevronDown, Save, History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { base44 } from '@/api/base44Client';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';

const PROPERTY_PACKAGES = [
  'Peng-Robinson', 'Peng-Robinson (Stryjek-Vera 2)', 'Soave-Redlich-Kwong',
  'Lee-Kesler-Plocker', 'NRTL', 'UNIQUAC', 'Modified UNIQUAC (UNIFAC)',
  'CoolProp', 'Steam Tables (IAPWS-IF97)',
];

const UNIT_OPS = [
  { id: 'mixer', label: 'Mixer', icon: '⊕' },
  { id: 'splitter', label: 'Splitter / Tee', icon: '⊻' },
  { id: 'heater', label: 'Heater', icon: '♨' },
  { id: 'cooler', label: 'Cooler', icon: '❄' },
  { id: 'heatex', label: 'Heat Exchanger', icon: '⇌' },
  { id: 'distil', label: 'Distillation Column', icon: '⬛' },
  { id: 'flash', label: 'Flash Drum', icon: '◈' },
  { id: 'compressor', label: 'Compressor', icon: '▲' },
  { id: 'pump', label: 'Pump', icon: '⟳' },
  { id: 'valve', label: 'Valve', icon: '◇' },
  { id: 'reactor_conv', label: 'Conversion Reactor', icon: '⚗' },
  { id: 'reactor_equil', label: 'Equilibrium Reactor', icon: '⚖' },
];

const COMMON_COMPOUNDS = [
  'Water', 'Ethanol', 'Methanol', 'Benzene', 'Toluene', 'n-Hexane',
  'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 'Methane', 'Ethane', 'Propane',
  'n-Butane', 'Acetone', 'Acetic Acid', 'Ammonia', 'Oxygen', 'Chlorine',
];

function generateScript({ simName, propPackage, compounds, streams, unitOps }) {
  const cList = compounds.map(c => `"${c}"`).join(', ');

  const streamBlocks = streams.map(s => `
# Stream: ${s.name}
${s.varName} = flowsheet.AddObject(ObjectType.MaterialStream, 100, 100, "${s.name}")
${s.varName}.SetOverallCompoundMoleFractions([${s.moleFracs}])
${s.varName}.SetPressure(${s.pressure || 101325})
${s.varName}.SetTemperature(${s.temperature || 298.15})
${s.varName}.SetMassFlow(${s.massFlow || 1.0})`).join('\n');

  const unitOpBlocks = unitOps.map(op => `
# Unit Operation: ${op.name} (${op.type})
${op.varName} = flowsheet.AddObject(ObjectType.${opTypeMap[op.type] || 'Mixer'}, 200, 200, "${op.name}")`).join('\n');

  return `# ============================================================
# DWSIM Simulation Script — Generated by Suttain
# Simulation: ${simName || 'My Process'}
# Property Package: ${propPackage}
# Compounds: ${compounds.join(', ')}
# ============================================================
# Requirements: DWSIM v10+, Python FluentAPI
# Run via: python thisscript.py  OR paste into DWSIM Script Operation
# ============================================================

import clr, os, sys

# --- Update this path to your DWSIM installation directory ---
dwsim_path = r"C:\\Users\\Public\\DWSIM"  # Windows default
# dwsim_path = "/usr/local/lib/dwsim"  # Linux
# dwsim_path = "/Applications/DWSIM.app/Contents/Resources"  # macOS

sys.path.append(dwsim_path)
clr.AddReference("DWSIM.Automation")
clr.AddReference("DWSIM.Interfaces")
clr.AddReference("DWSIM.GlobalSettings")
clr.AddReference("DWSIM.SharedClasses")
clr.AddReference("DWSIM.Thermodynamics")
clr.AddReference("DWSIM.UnitOperations")
clr.AddReference("CapeOpen.v1_1")

from DWSIM.Automation import Automation3
from DWSIM.Interfaces.Enums.GraphicObjects import ObjectType
from System import String, Double

# --- Initialize DWSIM Automation ---
interf = Automation3()
sim = interf.CreateFlowsheet()

# --- Add Compounds ---
for compound in [${cList}]:
    sim.AddCompound(compound)

# --- Property Package ---
pp = sim.CreateAndAddPropertyPackage("${propPackage}")

${streamBlocks || '# (No streams configured)'}

${unitOpBlocks || '# (No unit operations configured)'}

# --- Solve Flowsheet ---
errors = sim.SolveFlowsheet()
if errors:
    print("Solver warnings/errors:")
    for e in errors:
        print(" -", e)
else:
    print("Simulation solved successfully!")

# --- Print Stream Results ---
for stream_name in sim.GetFlowsheetSimulationObjectList():
    obj = sim.GetFlowsheetSimulationObject(stream_name)
    if hasattr(obj, "GetMassFlow"):
        print(f"Stream '{stream_name}': T={obj.GetTemperature():.2f} K, P={obj.GetPressure():.0f} Pa, F={obj.GetMassFlow():.4f} kg/s")

# --- Save Simulation File ---
output_path = r"${simName || 'my_simulation'}.dwxml"
interf.SaveFlowsheet(sim, output_path, True)
print(f"Saved: {output_path}")
`;
}

const opTypeMap = {
  mixer: 'Mixer', splitter: 'NodeIn', heater: 'Heater', cooler: 'Cooler',
  heatex: 'HeatExchanger', distil: 'DistillationColumn', flash: 'Flash2',
  compressor: 'Compressor', pump: 'Pump', valve: 'Valve',
  reactor_conv: 'ConversionReactor', reactor_equil: 'EquilibriumReactor',
};

export default function DWSIMScriptBuilder() {
  const [simName, setSimName] = useState('');
  const [propPackage, setPropPackage] = useState('Peng-Robinson');
  const [compounds, setCompounds] = useState([]);
  const [customCompound, setCustomCompound] = useState('');
  const [streams, setStreams] = useState([]);
  const [selectedOps, setSelectedOps] = useState([]);
  const [copied, setCopied] = useState(false);
  const [showScript, setShowScript] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savedMsg, setSavedMsg] = useState(false);

  const saveToHistory = async () => {
    setSaving(true);
    try {
      await base44.entities.DWSIMSimulationHistory.create({
        title: simName || `Script Builder — ${compounds.slice(0, 3).join(', ') || 'New Simulation'}`,
        sim_source: 'script_builder',
        script,
        config: { simName, propPackage, compounds, streams, selectedOps },
      });
      setSavedMsg(true);
      setTimeout(() => setSavedMsg(false), 3000);
    } finally {
      setSaving(false);
    }
  };

  const script = generateScript({ simName, propPackage, compounds, streams, unitOps: selectedOps });

  const addCompound = (c) => {
    if (c && !compounds.includes(c)) setCompounds([...compounds, c]);
    setCustomCompound('');
  };

  const addStream = () => {
    const id = Date.now();
    setStreams([...streams, {
      id, name: `Stream-${streams.length + 1}`, varName: `s${streams.length + 1}`,
      temperature: 298.15, pressure: 101325, massFlow: 1.0, moleFracs: '',
    }]);
  };

  const updateStream = (id, field, val) => {
    setStreams(streams.map(s => s.id === id ? { ...s, [field]: val } : s));
  };

  const toggleOp = (op) => {
    const exists = selectedOps.find(o => o.type === op.id);
    if (exists) {
      setSelectedOps(selectedOps.filter(o => o.type !== op.id));
    } else {
      const count = selectedOps.filter(o => o.type === op.id).length;
      setSelectedOps([...selectedOps, {
        type: op.id, name: `${op.label}-${count + 1}`,
        varName: `${op.id}${count + 1}`,
      }]);
    }
  };

  const copyScript = () => {
    navigator.clipboard.writeText(script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadScript = () => {
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${simName || 'dwsim_simulation'}.py`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4 text-sm text-blue-800">
        Configure your simulation parameters below, then generate a Python FluentAPI script ready to run in DWSIM.
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left column */}
        <div className="space-y-5">
          {/* Simulation name */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
            <h3 className="font-bold text-[#00281E] text-sm mb-3">Simulation Name</h3>
            <Input
              value={simName}
              onChange={e => setSimName(e.target.value)}
              placeholder="e.g. Ethanol Distillation"
              className="text-sm"
            />
          </div>

          {/* Property package */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
            <h3 className="font-bold text-[#00281E] text-sm mb-3">Thermodynamic Package</h3>
            <select
              value={propPackage}
              onChange={e => setPropPackage(e.target.value)}
              className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-[#007850]"
            >
              {PROPERTY_PACKAGES.map(p => (
                <option key={p} value={p}>{p}</option>
              ))}
            </select>
          </div>

          {/* Compounds */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
            <h3 className="font-bold text-[#00281E] text-sm mb-3">Compounds</h3>
            <div className="flex flex-wrap gap-2 mb-3">
              {COMMON_COMPOUNDS.map(c => (
                <button
                  key={c}
                  onClick={() => addCompound(c)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-medium border transition-colors ${
                    compounds.includes(c)
                      ? 'bg-[#007850] text-white border-[#007850]'
                      : 'bg-slate-50 text-slate-600 border-slate-200 hover:border-[#007850] hover:text-[#007850]'
                  }`}
                >
                  {c}
                </button>
              ))}
            </div>
            <div className="flex gap-2">
              <Input
                value={customCompound}
                onChange={e => setCustomCompound(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && addCompound(customCompound)}
                placeholder="Add custom compound..."
                className="text-xs"
              />
              <Button size="sm" onClick={() => addCompound(customCompound)} className="bg-[#007850] text-white hover:bg-[#005f3e]">
                <Plus className="w-4 h-4" />
              </Button>
            </div>
            {compounds.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-3">
                {compounds.map(c => (
                  <span key={c} className="flex items-center gap-1 bg-[#EDF7F2] border border-[#007850]/30 text-[#007850] text-xs px-2 py-0.5 rounded-full font-medium">
                    {c}
                    <button onClick={() => setCompounds(compounds.filter(x => x !== c))} className="hover:text-red-500">
                      <Trash2 className="w-2.5 h-2.5" />
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right column */}
        <div className="space-y-5">
          {/* Unit Operations */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
            <h3 className="font-bold text-[#00281E] text-sm mb-3">Unit Operations</h3>
            <div className="grid grid-cols-2 gap-2">
              {UNIT_OPS.map(op => {
                const active = selectedOps.some(o => o.type === op.id);
                return (
                  <button
                    key={op.id}
                    onClick={() => toggleOp(op)}
                    className={`flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-medium border transition-colors text-left ${
                      active
                        ? 'bg-violet-600 text-white border-violet-600'
                        : 'bg-slate-50 text-slate-700 border-slate-200 hover:border-violet-400'
                    }`}
                  >
                    <span className="text-sm">{op.icon}</span>
                    {op.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Streams */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-bold text-[#00281E] text-sm">Material Streams</h3>
              <Button size="sm" variant="outline" onClick={addStream} className="text-xs gap-1">
                <Plus className="w-3 h-3" /> Add Stream
              </Button>
            </div>
            {streams.length === 0 ? (
              <p className="text-xs text-slate-400 text-center py-4">No streams added yet.</p>
            ) : (
              <div className="space-y-3">
                {streams.map(s => (
                  <div key={s.id} className="bg-slate-50 rounded-xl p-3 space-y-2">
                    <div className="flex items-center justify-between">
                      <Input
                        value={s.name}
                        onChange={e => updateStream(s.id, 'name', e.target.value)}
                        className="text-xs font-semibold h-7 w-36 border-0 bg-transparent p-0 focus-visible:ring-0"
                      />
                      <button onClick={() => setStreams(streams.filter(x => x.id !== s.id))} className="text-slate-400 hover:text-red-500">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                    <div className="grid grid-cols-3 gap-2">
                      <div>
                        <label className="text-[10px] text-slate-400 block mb-0.5">Temp (K)</label>
                        <Input value={s.temperature} onChange={e => updateStream(s.id, 'temperature', e.target.value)} className="text-xs h-7" />
                      </div>
                      <div>
                        <label className="text-[10px] text-slate-400 block mb-0.5">Press (Pa)</label>
                        <Input value={s.pressure} onChange={e => updateStream(s.id, 'pressure', e.target.value)} className="text-xs h-7" />
                      </div>
                      <div>
                        <label className="text-[10px] text-slate-400 block mb-0.5">Flow (kg/s)</label>
                        <Input value={s.massFlow} onChange={e => updateStream(s.id, 'massFlow', e.target.value)} className="text-xs h-7" />
                      </div>
                    </div>
                    <div>
                      <label className="text-[10px] text-slate-400 block mb-0.5">Mole fractions (comma-separated, same order as compounds)</label>
                      <Input value={s.moleFracs} onChange={e => updateStream(s.id, 'moleFracs', e.target.value)} placeholder="e.g. 0.7, 0.3" className="text-xs h-7" />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Generate script */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
          <h3 className="font-bold text-[#00281E] text-sm">Generated Python Script</h3>
          <div className="flex gap-2 flex-wrap">
            <Button size="sm" variant="outline" onClick={() => setShowScript(!showScript)} className="text-xs gap-1">
              <ChevronDown className="w-3 h-3" />
              {showScript ? 'Hide' : 'Preview'}
            </Button>
            <Button size="sm" variant="outline" onClick={copyScript} className="text-xs gap-1">
              {copied ? <Check className="w-3 h-3 text-green-600" /> : <Copy className="w-3 h-3" />}
              {copied ? 'Copied' : 'Copy'}
            </Button>
            <Button size="sm" variant="outline" onClick={saveToHistory} disabled={saving} className="text-xs gap-1 border-[#007850] text-[#007850] hover:bg-[#007850]/10">
              {savedMsg ? <Check className="w-3 h-3 text-green-600" /> : <Save className="w-3 h-3" />}
              {savedMsg ? 'Saved' : saving ? 'Saving...' : 'Save'}
            </Button>
            <Button size="sm" onClick={downloadScript} className="text-xs gap-1 bg-[#007850] text-white hover:bg-[#005f3e]">
              <Download className="w-3 h-3" /> Download .py
            </Button>
            <Link to={createPageUrl('SimulationHistory')}>
              <Button size="sm" variant="ghost" className="text-xs gap-1 text-slate-500 hover:text-[#007850]">
                <History className="w-3 h-3" /> History
              </Button>
            </Link>
          </div>
        </div>
        {showScript && (
          <pre className="text-xs text-slate-700 bg-slate-950 text-green-400 p-5 overflow-x-auto max-h-[500px] leading-relaxed">
            {script}
          </pre>
        )}
      </div>
    </div>
  );
}