import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { exportShortlist } from '@/components/drug-discovery/discoveryData';
export default function DiscoveryShortlist({ state: s }) {
  const [showApi, setShowApi] = useState(false);
  return <section aria-labelledby="discovery-shortlist-title">
    <h1 id="discovery-shortlist-title" className="mb-1">Shortlist</h1><p className="text-muted-foreground mb-5">Compare your selected example candidates side by side</p>
    {s.actionError && <p role="alert" className="mb-4 text-sm text-destructive">{s.actionError}</p>}
    {s.shortlistLoading ? <p role="status">Loading your saved shortlist…</p> : s.shortlistError ? <p role="alert">Could not load your shortlist. <button onClick={s.refresh} className="underline">Retry</button></p> : !s.shortlist.length ? <div className="text-center py-12 border border-border rounded-lg"><div aria-hidden="true" className="w-11 h-11 mx-auto mb-4 rounded-lg border border-accent text-accent bg-accent/5 font-mono flex items-center justify-center">Sl</div><h2 className="!text-lg">Nothing shortlisted yet</h2><p className="text-sm text-muted-foreground mt-1">Select candidates, then compare them here.</p><button onClick={() => s.navigate('candidates')} className="research-secondary mt-4">Go to candidates</button></div> : <>
      <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{s.shortlist.map(c => <article key={c.id} className="border border-border rounded-lg p-4"><div className="flex items-center justify-between gap-2 mb-3"><h2 className="!text-base">{c.id}</h2><button aria-label={`Remove ${c.id} from shortlist`} onClick={() => s.removeFromShortlist(c.id)} disabled={s.saving} className="text-xs text-muted-foreground underline disabled:opacity-40">Remove</button></div><dl className="divide-y divide-border">{[['Binding score', c.score.toFixed(1)], ['ADMET risk', c.risk], ['Similarity', `${c.sim}%`], ['Synthesizability', c.synth.toFixed(2)]].map(([label, value]) => <div key={label} className="flex justify-between gap-2 py-2 text-xs"><dt className="text-muted-foreground">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl></article>)}</div>
      <div className="flex flex-wrap gap-3 mt-5"><button onClick={() => exportShortlist(s.shortlist)} className="research-primary bg-primary text-primary-foreground">Export shortlist (.csv)</button><button onClick={() => setShowApi(true)} className="research-secondary">Pull via API</button></div><p className="text-xs text-muted-foreground mt-3">CSV exports demonstration values. SDF export is unavailable because these examples have no molecular structures.</p>
    </>}
    <Dialog open={showApi} onOpenChange={setShowApi}><DialogContent><DialogHeader><DialogTitle>Shortlist API availability</DialogTitle><DialogDescription>Your shortlist is saved privately to your account, but a shortlist API endpoint is not available. Export a CSV to use these illustrative values outside the app.</DialogDescription></DialogHeader><Link to="/APIPortal" className="research-secondary" onClick={() => setShowApi(false)}>View existing research API documentation</Link></DialogContent></Dialog>
  </section>;
}