import { RISK_STYLE } from '@/components/drug-discovery/discoveryData';
export default function DiscoveryCandidates({ state: s }) {
  const count = Object.values(s.selected).filter(Boolean).length;
  return <section aria-labelledby="discovery-candidates-title">
    <h1 id="discovery-candidates-title" className="mb-1">Candidates</h1><p className="text-muted-foreground mb-4">Preview illustrative candidates — these are not results from submitted jobs</p>
    <div className="flex flex-wrap gap-3 items-end justify-between mb-4"><div className="flex flex-wrap gap-3">
      <div><label htmlFor="drug-risk" className="text-xs block mb-1">ADMET risk</label><select id="drug-risk" value={s.riskFilter} onChange={e => s.setRiskFilter(e.target.value)} className="simulation-control"><option value="all">All ADMET risk</option><option value="low">Low only</option><option value="exclude_high">Exclude high risk</option></select></div>
      <div><label htmlFor="drug-sort" className="text-xs block mb-1">Sort candidates</label><select id="drug-sort" value={s.sortBy} onChange={e => s.setSortBy(e.target.value)} className="simulation-control"><option value="score">Binding score</option><option value="sim">Similarity</option><option value="synth">Synthesizability</option></select></div>
    </div><p className="text-xs text-muted-foreground" aria-live="polite">{s.visibleCandidates.length} candidates</p></div>
    <div className="overflow-x-auto"><table className="w-full text-sm min-w-[640px]"><caption className="sr-only">Demonstration compounds with illustrative binding and risk values</caption><thead><tr className="text-left text-xs text-muted-foreground border-b border-border">{['Select', 'Compound', 'Predicted binding', 'ADMET risk', 'Similarity'].map(label => <th key={label} scope="col" className="p-2">{label}</th>)}</tr></thead><tbody>{s.visibleCandidates.map(c => <tr key={c.id} className="border-b border-border hover:bg-muted"><td className="p-2"><input type="checkbox" aria-label={`Select ${c.id}`} checked={!!s.selected[c.id]} onChange={() => s.toggleSelect(c.id)} /></td><th scope="row" className="p-2 font-medium text-left">{c.id}</th><td className="p-2">{c.score.toFixed(1)}</td><td className="p-2"><span className={`text-xs px-2 py-1 rounded font-mono ${RISK_STYLE[c.risk]}`}>{c.risk}</span></td><td className="p-2">{c.sim}% · {c.drug}</td></tr>)}</tbody></table></div>
    <p className="text-xs text-muted-foreground mt-4">Fixed example values, not calculated binding affinity, clinical safety, or validated ADMET predictions.</p>
    {s.actionError && <p role="alert" className="mt-3 text-sm text-destructive">{s.actionError}</p>}
    {s.shortlistError && <p role="alert" className="mt-3 text-sm text-destructive">Could not load your saved shortlist. <button onClick={s.refresh} className="underline">Retry</button></p>}
    {count > 0 && <div className="sticky bottom-0 mt-4 bg-foreground text-background rounded-lg p-4 flex flex-wrap gap-3 items-center justify-between"><span className="text-sm" aria-live="polite">{count} selected (including filtered-out rows)</span><button onClick={s.addSelectedToShortlist} disabled={s.saving || s.shortlistLoading || !!s.shortlistError} className="research-primary bg-primary text-primary-foreground disabled:opacity-40">{s.saving ? 'Saving…' : 'Save & compare selected →'}</button></div>}
  </section>;
}