export default function DiscoveryDashboard({ navigate, start, metrics }) {
  const data = metrics.data;
  const values = [[data?.activeJobs, 'Active screening jobs'], [data?.compoundsScreened30d, 'Compounds screened (30d)'], [data?.candidatesShortlisted, 'Candidates shortlisted'], [data?.avgTimeToShortlist ?? '—', 'Avg. time to shortlist']];
  return <section aria-labelledby="discovery-dashboard-title">
    <h1 id="discovery-dashboard-title" className="mb-1">Dashboard</h1><p className="text-muted-foreground mb-5">Your screening activity and recent shortlists</p>
    <button onClick={() => navigate('how')} className="w-full text-left mb-5 rounded-lg border border-accent/30 bg-accent/5 p-4 text-sm flex flex-col sm:flex-row gap-3 justify-between"><span>New here? See how AI-powered drug discovery works and how this tool walks you through it.</span><span className="text-accent font-medium shrink-0">How it works →</span></button>
    <p className="text-xs font-mono text-muted-foreground mb-3">Your saved activity · Only real compute submissions count</p>
    {metrics.isError ? <div role="alert" className="mb-5 text-sm text-destructive">Could not load your activity. <button onClick={() => metrics.refetch()} className="underline">Retry</button></div> : <div aria-busy={metrics.isPending} className="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-4">{values.map(([number, label]) => <div key={label} className="border border-border rounded-lg p-4"><div className="text-2xl font-medium text-primary">{metrics.isPending ? '…' : typeof number === 'number' ? number.toLocaleString() : number}</div><p className="text-xs text-muted-foreground mt-1">{label}</p></div>)}</div>}
    {metrics.isPending && <p role="status" className="text-sm text-muted-foreground mb-4">Loading your activity…</p>}
    {data && <div className="text-xs text-muted-foreground space-y-2 mb-6"><p>{data.totalJobs === 0 ? 'No real screening jobs yet. Demonstrations are excluded.' : 'Counts reflect your saved compute records.'} {data.candidatesShortlisted === 0 ? 'Your shortlist is empty.' : 'Shortlist counts include your saved illustrative candidates.'}</p><p>Screened compounds use reported counts, not requested limits. Average time uses submission-to-completion duration; — means no completed jobs.</p>{!data.computeAvailable && <p>Real screening compute is not connected. You can search targets and save candidates, but cannot launch compute yet.</p>}</div>}
    <button onClick={start} className="research-primary bg-primary text-primary-foreground">Define a new target →</button>
  </section>;
}