import React, { useState } from 'react';
import { ShoppingCart, Loader2, Download, X, CheckCircle, AlertTriangle, Sparkles, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { base44 } from '@/api/base44Client';

export default function GroceryListExport({ scans, onClose }) {
    const [loading, setLoading] = useState(false);
    const [groceryList, setGroceryList] = useState(null);
    const [copied, setCopied] = useState(false);

    const safeScans = scans.filter(s => s.chemical_threat_level === 'safe' || s.chemical_threat_level === 'low');
    const riskyScans = scans.filter(s => s.chemical_threat_level === 'moderate' || s.chemical_threat_level === 'high');

    const generate = async () => {
        setLoading(true);
        try {
            const safeFoods = safeScans.map(s => s.food_name).join(', ') || 'none';
            const riskyFoods = riskyScans.map(s => `${s.food_name} (${s.chemical_threat_level} risk)`).join(', ') || 'none';

            const result = await base44.integrations.Core.InvokeLLM({
                prompt: `You are a nutrition expert helping a user build a healthy weekly grocery list based on their food scan history.

Safe/low-risk foods they ate this week: ${safeFoods}
Moderate/high-risk foods they ate this week: ${riskyFoods}

Generate a practical weekly grocery shopping list that:
1. Includes ingredients to recreate or continue eating the safe foods
2. For each risky food, suggest a healthier alternative ingredient to buy instead (same category, better profile)
3. Group items by store section

Return JSON only.`,
                response_json_schema: {
                    type: 'object',
                    properties: {
                        safe_items: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    item: { type: 'string' },
                                    section: { type: 'string' },
                                    note: { type: 'string' }
                                }
                            }
                        },
                        alternatives: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    original_food: { type: 'string' },
                                    alternative: { type: 'string' },
                                    section: { type: 'string' },
                                    reason: { type: 'string' }
                                }
                            }
                        },
                        sections: {
                            type: 'array',
                            items: { type: 'string' }
                        }
                    }
                }
            });

            setGroceryList(result);
        } catch (e) {
            console.error('Grocery list generation failed:', e);
        } finally {
            setLoading(false);
        }
    };

    const exportAsText = () => {
        if (!groceryList) return;

        const lines = ['🛒 WEEKLY GROCERY LIST', '══════════════════════', ''];

        if (groceryList.safe_items?.length) {
            lines.push('✅ KEEP BUYING (Safe Foods)');
            groceryList.safe_items.forEach(item => {
                lines.push(`  • ${item.item}${item.note ? ` — ${item.note}` : ''}`);
            });
            lines.push('');
        }

        if (groceryList.alternatives?.length) {
            lines.push('🔄 HEALTHIER SWAPS (Replace High-Risk Items)');
            groceryList.alternatives.forEach(alt => {
                lines.push(`  • ${alt.alternative} (instead of ${alt.original_food})`);
                if (alt.reason) lines.push(`    ↳ ${alt.reason}`);
            });
            lines.push('');
        }

        lines.push('Generated by Suttain Food Analysis');

        const text = lines.join('\n');
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadTxt = () => {
        if (!groceryList) return;
        const lines = ['🛒 WEEKLY GROCERY LIST', '══════════════════════', ''];

        if (groceryList.safe_items?.length) {
            lines.push('✅ KEEP BUYING (Safe Foods)');
            groceryList.safe_items.forEach(item => {
                lines.push(`  • ${item.item}${item.note ? ` — ${item.note}` : ''}`);
            });
            lines.push('');
        }

        if (groceryList.alternatives?.length) {
            lines.push('🔄 HEALTHIER SWAPS (Replace High-Risk Items)');
            groceryList.alternatives.forEach(alt => {
                lines.push(`  • ${alt.alternative} (instead of ${alt.original_food})`);
                if (alt.reason) lines.push(`    ↳ ${alt.reason}`);
            });
        }

        lines.push('', 'Generated by Suttain Food Analysis');

        const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'grocery-list.txt';
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/50 px-0 sm:px-4">
            <div className="bg-white w-full sm:max-w-lg rounded-t-3xl sm:rounded-2xl max-h-[90vh] flex flex-col">
                {/* Header */}
                <div className="flex items-center justify-between p-4 border-b border-slate-100 flex-shrink-0">
                    <div className="flex items-center gap-2">
                        <div className="w-8 h-8 bg-teal-100 rounded-xl flex items-center justify-center">
                            <ShoppingCart className="w-4 h-4 text-teal-700" />
                        </div>
                        <div>
                            <h2 className="font-bold text-slate-900 text-sm">Weekly Grocery List</h2>
                            <p className="text-xs text-slate-500">Based on your food history</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-700">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <div className="overflow-y-auto flex-1 p-4 space-y-4">
                    {/* Stats */}
                    <div className="grid grid-cols-2 gap-3">
                        <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-3 text-center">
                            <p className="text-2xl font-extrabold text-emerald-700">{safeScans.length}</p>
                            <p className="text-xs text-emerald-600 font-medium flex items-center justify-center gap-1 mt-0.5">
                                <CheckCircle className="w-3 h-3" /> Safe foods to keep
                            </p>
                        </div>
                        <div className="bg-red-50 border border-red-200 rounded-xl p-3 text-center">
                            <p className="text-2xl font-extrabold text-red-700">{riskyScans.length}</p>
                            <p className="text-xs text-red-600 font-medium flex items-center justify-center gap-1 mt-0.5">
                                <AlertTriangle className="w-3 h-3" /> Items needing swaps
                            </p>
                        </div>
                    </div>

                    {!groceryList && !loading && (
                        <div className="bg-slate-50 rounded-2xl p-4 text-center space-y-3">
                            <Sparkles className="w-8 h-8 text-teal-500 mx-auto" />
                            <p className="text-sm text-slate-600">
                                AI will build you a personalized grocery list — keeping safe foods and swapping out the risky ones with healthier alternatives.
                            </p>
                            <Button
                                onClick={generate}
                                className="w-full bg-gradient-to-r from-[#02988C] to-[#09D2FF] text-white font-bold rounded-xl"
                            >
                                <Sparkles className="w-4 h-4 mr-2" /> Generate My List
                            </Button>
                        </div>
                    )}

                    {loading && (
                        <div className="flex flex-col items-center justify-center py-10 gap-3">
                            <Loader2 className="w-7 h-7 animate-spin text-teal-500" />
                            <p className="text-sm text-slate-500">Building your personalized grocery list...</p>
                        </div>
                    )}

                    {groceryList && (
                        <div className="space-y-4">
                            {/* Safe items */}
                            {groceryList.safe_items?.length > 0 && (
                                <div>
                                    <div className="flex items-center gap-2 mb-2">
                                        <CheckCircle className="w-4 h-4 text-emerald-600" />
                                        <p className="text-sm font-bold text-slate-800">Keep Buying — Safe Foods</p>
                                    </div>
                                    <div className="space-y-1.5">
                                        {groceryList.safe_items.map((item, i) => (
                                            <div key={i} className="flex items-start gap-2 bg-emerald-50 border border-emerald-100 rounded-xl px-3 py-2">
                                                <span className="text-emerald-500 mt-0.5 text-sm">✓</span>
                                                <div>
                                                    <p className="text-sm font-semibold text-slate-800">{item.item}</p>
                                                    {item.note && <p className="text-xs text-slate-500">{item.note}</p>}
                                                    <p className="text-[10px] text-emerald-600 font-medium">{item.section}</p>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Alternatives */}
                            {groceryList.alternatives?.length > 0 && (
                                <div>
                                    <div className="flex items-center gap-2 mb-2">
                                        <AlertTriangle className="w-4 h-4 text-amber-500" />
                                        <p className="text-sm font-bold text-slate-800">Healthier Swaps</p>
                                    </div>
                                    <div className="space-y-2">
                                        {groceryList.alternatives.map((alt, i) => (
                                            <div key={i} className="bg-amber-50 border border-amber-100 rounded-xl px-3 py-2.5">
                                                <div className="flex items-center gap-1.5 mb-1">
                                                    <span className="text-xs line-through text-red-400">{alt.original_food}</span>
                                                    <span className="text-xs text-slate-400">→</span>
                                                    <span className="text-sm font-bold text-slate-800">{alt.alternative}</span>
                                                </div>
                                                {alt.reason && <p className="text-xs text-slate-500">{alt.reason}</p>}
                                                <p className="text-[10px] text-amber-600 font-medium mt-0.5">{alt.section}</p>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* Export Actions */}
                {groceryList && (
                    <div className="p-4 border-t border-slate-100 flex gap-2 flex-shrink-0">
                        <Button onClick={exportAsText} variant="outline" className="flex-1 text-sm">
                            <Copy className="w-4 h-4 mr-1.5" /> {copied ? 'Copied!' : 'Copy'}
                        </Button>
                        <Button onClick={downloadTxt} className="flex-1 bg-[#02988C] hover:bg-[#017a70] text-white text-sm">
                            <Download className="w-4 h-4 mr-1.5" /> Download
                        </Button>
                    </div>
                )}
            </div>
        </div>
    );
}