import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

const PUBCHEM_PROPS = 'MolecularFormula,MolecularWeight,CanonicalSMILES,IUPACName,XLogP,TPSA,HBondDonorCount,HBondAcceptorCount,RotatableBondCount,HeavyAtomCount,Charge';

async function fetchPubChemProps(input) {
  const isSmiles = /[()=#\[\]\\]/.test(input) || input.length > 30;
  const url = isSmiles
    ? `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/${encodeURIComponent(input)}/property/${PUBCHEM_PROPS}/JSON`
    : `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodeURIComponent(input)}/property/${PUBCHEM_PROPS}/JSON`;
  const res = await fetch(url);
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`PubChem lookup failed (${res.status}): ${txt.slice(0, 200)}`);
  }
  const data = await res.json();
  const props = data?.PropertyTable?.Properties?.[0];
  if (!props) throw new Error('No compound found for the given input.');
  return props;
}

function checkLipinski(p) {
  const violations = [];
  if (p.MolecularWeight > 500) violations.push('Molecular weight > 500 Da');
  if (p.XLogP > 5) violations.push('XLogP > 5');
  if (p.HBondDonorCount > 5) violations.push('H-bond donors > 5');
  if (p.HBondAcceptorCount > 10) violations.push('H-bond acceptors > 10');
  return { passes: violations.length === 0, violations };
}

function generateEngineInput(molecule, engine, props) {
  const smiles = props.CanonicalSMILES || molecule;
  const mw = props.MolecularWeight || 'unknown';
  const formula = props.MolecularFormula || 'unknown';
  if (engine === 'gromacs') {
    return `; GROMACS topology input — generated by Suttain
; Molecule: ${molecule}
; Formula: ${formula}  MW: ${mw} g/mol
; SMILES: ${smiles}
; NOTE: This file is a scaffold. You must run pdb2gmx/gmx pdb2gmx
; on a proper 3D structure and parameterize with a forcefield (e.g. OPLS-AA).

[ moleculetype ]
; Name    nrexcl
SUTTAIN   3

[ atoms ]
; Replace with actual atom entries from your 3D structure

[ system ]
${molecule} in solvent

[ molecules ]
; Compound   #mols
SUTTAIN      1
`;
  }
  if (engine === 'quantum_espresso') {
    return `&control
  prefix = 'suttain', pseudo_dir = './'
/
&system
  ibrav = 0, nat = , ntyp = ,
  ecutwfc = 30.0, ecutrho = 240.0,
/
&electrons
  conv_thr = 1.0d-8,
/
ATOMIC_SPECIES
; Add species here
CELL_PARAMETERS
; Add lattice vectors here
ATOMIC_POSITIONS
; Add atom positions here (from SMILES: ${smiles})
K_POINTS automatic
  4 4 4 0 0 0
`;
  }
  if (engine === 'lammps') {
    return `# LAMMPS input — generated by Suttain
# Molecule: ${molecule} (SMILES: ${smiles})
# Formula: ${formula}  MW: ${mw}

units real
atom_style full
boundary p p p

# Read structure
read_data suttain.data

# Forcefield
pair_style lj/cut 10.0
bond_style harmonic
angle_style harmonic
dihedral_style opls

# Settings
neighbor 2.0 bin
neigh_modify delay 0 every 1 check yes

timestep 1.0

# Minimization
minimize 1.0e-4 1.0e-6 1000 10000

# Dynamics
fix 1 all npt temp 300.0 300.0 100.0 iso 1.0 1.0 1000.0
run 10000
`;
  }
  return `# Unknown engine: ${engine}`;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { mode, molecule, molecule_b, engine } = body;

    if (!molecule) return Response.json({ error: 'molecule is required' }, { status: 400 });

    if (mode === 'descriptors') {
      const props = await fetchPubChemProps(molecule);
      const lipinski = checkLipinski(props);
      return Response.json({
        source: 'PubChem',
        formula: props.MolecularFormula,
        molecular_weight: props.MolecularWeight,
        smiles: props.CanonicalSMILES,
        iupac_name: props.IUPACName,
        logp: props.XLogP,
        tpsa: props.TPSA,
        h_bond_donors: props.HBondDonorCount,
        h_bond_acceptors: props.HBondAcceptorCount,
        rotatable_bonds: props.RotatableBondCount,
        heavy_atoms: props.HeavyAtomCount,
        formal_charge: props.Charge,
        lipinski: lipinski
      });
    }

    if (mode === 'compare') {
      if (!molecule_b) return Response.json({ error: 'molecule_b is required for compare mode' }, { status: 400 });
      const [a, b] = await Promise.all([fetchPubChemProps(molecule), fetchPubChemProps(molecule_b)]);
      return Response.json({
        source: 'PubChem',
        molecule_a: {
          input: molecule, formula: a.MolecularFormula, molecular_weight: a.MolecularWeight,
          logp: a.XLogP, tpsa: a.TPSA, drug_like: checkLipinski(a).passes
        },
        molecule_b: {
          input: molecule_b, formula: b.MolecularFormula, molecular_weight: b.MolecularWeight,
          logp: b.XLogP, tpsa: b.TPSA, drug_like: checkLipinski(b).passes
        }
      });
    }

    if (mode === 'engine_input') {
      if (!engine) return Response.json({ error: 'engine is required for engine_input mode' }, { status: 400 });
      const validEngines = ['gromacs', 'quantum_espresso', 'lammps'];
      if (!validEngines.includes(engine)) return Response.json({ error: `engine must be one of: ${validEngines.join(', ')}` }, { status: 400 });
      let props;
      try { props = await fetchPubChemProps(molecule); } catch { props = { CanonicalSMILES: molecule, MolecularWeight: 'unknown', MolecularFormula: 'unknown' }; }
      const input_file = generateEngineInput(molecule, engine, props);
      return Response.json({
        source: 'Input file for external engine',
        engine,
        molecule,
        input_file,
        honest_note: 'This input file is a scaffold for an external HPC engine. It does not run in the browser. You must deploy it on a cluster with the corresponding software installed (GROMACS, Quantum ESPRESSO, or LAMMPS).'
      });
    }

    return Response.json({ error: `Unknown mode: ${mode}. Use descriptors, compare, or engine_input.` }, { status: 400 });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});