// Pricing catalog organised by product line (pillar).
// Each paid plan maps to a Stripe price key handled by createCheckoutSession.

export const PILLARS = [
  {
    id: 'core',
    label: 'Core',
    accent: '#02988C',
    fill: '#F0FDFA',
    tagline: 'Everyday chemical safety, product scanning, and formulation.',
  },
  {
    id: 'research',
    label: 'Research',
    accent: '#9531F5',
    fill: '#F5EEFF',
    tagline: 'Computational simulations, research workflows, and citation-ready exports.',
  },
];

export const PLANS_BY_PILLAR = {
  core: [
    {
      id: 'core_free',
      name: 'Core free',
      priceMonthly: '$0',
      priceYearly: '$0',
      priceSuffix: '',
      noteMonthly: 'No credit card required',
      noteYearly: 'No credit card required',
      description: 'Try the consumer tools with monthly limits.',
      features: [
        'Unlimited product scans',
        '3 simulations per month',
        '5 formula generations per month',
        'Ingredient database access',
      ],
      free: true,
      cta: 'Current plan',
    },
    {
      id: 'core',
      name: 'Suttain core',
      priceMonthly: '$4.99',
      priceYearly: '$3.99',
      priceSuffix: '/month',
      noteMonthly: 'Cancel anytime',
      noteYearly: 'Billed $47.88 per year, save 20%',
      description: 'Full access to the safety and formulation tools.',
      features: [
        'Unlimited simulations',
        'Unlimited formula generations',
        'Carbon tax simulator',
        'Saved history and workspace',
        'Email support',
      ],
      cta: 'Get core',
      priceKey: 'core_monthly',
      priceKeyYearly: 'core_yearly',
      popular: true,
    },
    {
      id: 'core_custom',
      name: 'Small business',
      priceMonthly: 'Custom',
      priceYearly: 'Custom',
      priceSuffix: '',
      noteMonthly: 'Volume pricing for teams',
      noteYearly: 'Volume pricing for teams',
      description: 'Tailored plans for small businesses with multiple seats.',
      features: [
        'Everything in Suttain core',
        'Multiple team seats',
        'Shared workspace and projects',
        'Bulk product scanning',
        'Priority email support',
        'Onboarding assistance',
      ],
      cta: 'Contact sales',
      custom: true,
    },
  ],
  research: [
    {
      id: 'research_free',
      name: 'Research free',
      priceMonthly: '$0',
      priceYearly: '$0',
      priceSuffix: '',
      noteMonthly: 'No credit card required',
      noteYearly: 'No credit card required',
      description: 'Explore research workflows with limited compute.',
      features: [
        '3 simulations per month',
        'DFT and MD workflows included within the free allowance',
      ],
      free: true,
      cta: 'Current plan',
    },
    {
      id: 'research',
      name: 'Suttain research',
      priceMonthly: '$49.99',
      priceYearly: '$39.99',
      priceSuffix: '/month',
      noteMonthly: 'Cancel anytime',
      noteYearly: 'Billed $479.90 per year, save 20%',
      description: 'Configure atomistic simulations, screen drug candidates, and connect your scripts through the Research API.',
      features: [
        'DFT and molecular dynamics workflow access',
        'Engine-specific inputs for local and HPC execution',
        'Drug target search, evidence screening, and shortlists',
        'Personal and shared team API keys',
        'API usage tracking and configurable request limits',
        'Research workspace and job tracking',
        'Citation-ready exports',
        'Full Core access included',
      ],
      cta: 'Get research',
      priceKey: 'research_monthly',
      priceKeyYearly: 'research_yearly',
      popular: true,
    },
  ],
};