// Pricing catalog organised by product line (pillar).
// Each paid plan maps to a Stripe price key handled by createCheckoutSession.

export const PILLARS = [
  {
    id: 'core',
    label: 'Core',
    accent: '#0F6E56',
    fill: '#E1F5EE',
    tagline: 'Everyday chemical safety, product scanning, and formulation.',
  },
  {
    id: 'research',
    label: 'Research',
    accent: '#534AB7',
    fill: '#EEEDFE',
    tagline: 'Simulation, molecular intelligence, and structural biology.',
  },
  {
    id: 'farm',
    label: 'Farm',
    accent: '#3B6D11',
    fill: '#EAF3DE',
    tagline: 'Crop diagnosis, weather intelligence, and field reports.',
  },
];

export const PLANS_BY_PILLAR = {
  core: [
    {
      id: 'core_free',
      name: 'Core free',
      priceMonthly: '$0',
      priceYearly: '$0',
      priceSuffix: '',
      noteMonthly: 'No credit card required',
      noteYearly: 'No credit card required',
      description: 'Try the consumer tools with monthly limits.',
      features: [
        'Unlimited product scans',
        '3 simulations per month',
        '5 formula generations per month',
        'Ingredient database access',
      ],
      free: true,
      cta: 'Current plan',
    },
    {
      id: 'core',
      name: 'Suttain core',
      priceMonthly: '$4.99',
      priceYearly: '$3.99',
      priceSuffix: '/month',
      noteMonthly: 'Cancel anytime',
      noteYearly: 'Billed $47.88 per year — save 20%',
      description: 'Full access to the safety and formulation tools.',
      features: [
        'Unlimited simulations',
        'Unlimited formula generations',
        'Carbon tax simulator',
        'Saved history and workspace',
        'Email support',
      ],
      cta: 'Get core',
      priceKey: 'core_monthly',
      priceKeyYearly: 'core_yearly',
      popular: true,
    },
  ],
  research: [
    {
      id: 'research_free',
      name: 'Research free',
      priceMonthly: '$0',
      priceYearly: '$0',
      priceSuffix: '',
      noteMonthly: 'No credit card required',
      noteYearly: 'No credit card required',
      description: 'Explore molecular data with limited compute.',
      features: [
        'Molecule analysis and search',
        'PubChem and ChEMBL lookups',
        '3 simulations per month',
        'No DFT or MD runs',
      ],
      free: true,
      cta: 'Current plan',
    },
    {
      id: 'research',
      name: 'Suttain research',
      priceMonthly: '$49.99',
      priceYearly: '$39.99',
      priceSuffix: '/month',
      noteMonthly: 'Cancel anytime',
      noteYearly: 'Billed $479.90 per year — save 20%',
      description: 'Computational studio, simulations, and structural biology.',
      features: [
        'Unlimited DFT and MD simulations',
        'Computational studio and job queue',
        'Structural biology suite',
        'Chemical comparison and SDS analyzer',
        'Citation-ready exports',
      ],
      cta: 'Get research',
      priceKey: 'research_monthly',
      priceKeyYearly: 'research_yearly',
      popular: true,
    },
  ],
  farm: [
    {
      id: 'farm_free',
      name: 'Farm free',
      priceMonthly: '$0',
      priceYearly: '$0',
      priceSuffix: '',
      noteMonthly: 'No credit card required',
      noteYearly: 'No credit card required',
      description: 'Basic field tools for a single farm.',
      features: [
        'One farm profile',
        '3 photo diagnoses per month',
        'Basic weather view',
        'Field history',
      ],
      free: true,
      cta: 'Current plan',
    },
    {
      id: 'farm',
      name: 'Suttain farm',
      priceMonthly: '$9.99',
      priceYearly: '$7.99',
      priceSuffix: '/month',
      noteMonthly: 'Cancel anytime',
      noteYearly: 'Billed $95.88 per year — save 20%',
      description: 'Field intelligence for growers and agronomists.',
      features: [
        'Unlimited photo crop diagnosis',
        'Weather and spray alerts',
        'Farm advisory chat',
        'Yield tracking and reports',
        'Multi-language support',
      ],
      cta: 'Get farm',
      priceKey: 'farm_monthly',
      priceKeyYearly: 'farm_yearly',
      popular: true,
    },
  ],
};