import { Beaker, Microscope, Terminal, Sprout, Building2, Zap } from 'lucide-react';

// One tab per product line. Each line lists only its own plans.
export const PRODUCT_LINES = [
  {
    id: 'consumer',
    label: 'Consumer',
    icon: Beaker,
    color: '#0F6E56',
    tagline: 'Formulating, compliance and scanning for your brand.',
    plans: [
      {
        id: 'consumer_free',
        name: 'Free',
        price: '$0',
        priceNote: 'No credit card required',
        description: 'Try the consumer tools before you commit.',
        features: [
          '3 simulations per month',
          '5 formula generations per month',
          'Unlimited product scans',
          'Ingredient database access',
        ],
        cta: 'Current plan',
        ctaDisabled: true,
        icon: Zap,
      },
      {
        id: 'consumer_paid',
        name: 'Consumer',
        priceMonthly: '$4.99',
        priceYearly: '$3.99',
        priceSuffix: '/month',
        priceNote: 'Cancel anytime',
        priceNoteYearly: 'Billed $47.88/year — save 20%',
        description: 'Full formulation and safety toolkit.',
        features: [
          'Unlimited formula generations',
          'Unlimited chemical simulations',
          'SuttainScan product analysis',
          'Carbon impact simulator',
          'Hydration intelligence',
          'Batch records and compliance',
        ],
        cta: 'Get Consumer',
        popular: true,
        priceKey: 'consumer_monthly',
        priceKeyYearly: 'consumer_yearly',
        icon: Beaker,
      },
    ],
  },
  {
    id: 'research',
    label: 'Research',
    icon: Microscope,
    color: '#534AB7',
    tagline: 'Molecular intelligence, simulation and structural biology.',
    plans: [
      {
        id: 'research_free',
        name: 'Free',
        price: '$0',
        priceNote: 'No credit card required',
        description: 'Explore molecular data and light simulations.',
        features: [
          'Molecular queries',
          '3 simulations per month',
          'Chemical library access',
          'Community support',
        ],
        cta: 'Current plan',
        ctaDisabled: true,
        icon: Zap,
      },
      {
        id: 'research_paid',
        name: 'Research',
        priceMonthly: '$49.99',
        priceYearly: '$39.99',
        priceSuffix: '/month',
        priceNote: 'Cancel anytime',
        priceNoteYearly: 'Billed $479.90/year — save 20%',
        description: 'The full computational research suite.',
        features: [
          'Unlimited simulations (DFT, MD)',
          'Computational Studio access',
          'Full structural biology suite',
          'Citation-ready exports',
          'Priority compute queue',
          'Lab workspace',
        ],
        cta: 'Get Research',
        popular: true,
        priceKey: 'research_monthly',
        priceKeyYearly: 'research_yearly',
        icon: Microscope,
      },
    ],
  },
  {
    id: 'api',
    label: 'API',
    icon: Terminal,
    color: '#993C1D',
    tagline: 'REST endpoints, SDKs and enterprise integrations.',
    plans: [
      {
        id: 'api_paid',
        name: 'API',
        priceMonthly: '$199.00',
        priceYearly: '$159.17',
        priceSuffix: '/month',
        priceNote: 'Cancel anytime',
        priceNoteYearly: 'Billed $1,910.00/year — save 20%',
        description: 'Programmatic access to the Suttain platform.',
        features: [
          'Compound lookup endpoints',
          'Hazard scoring and interaction checks',
          'Formula generation API',
          'Python, JavaScript and R SDKs',
          'Higher rate limits',
        ],
        cta: 'Get API access',
        popular: true,
        priceKey: 'api_monthly',
        priceKeyYearly: 'api_yearly',
        icon: Terminal,
      },
      {
        id: 'api_enterprise',
        name: 'Enterprise',
        price: 'Custom',
        priceNote: 'Contact us for a quote',
        description: 'Dedicated infrastructure for organizations.',
        features: [
          'White-label deployment',
          'Dedicated infrastructure',
          'SSO and unlimited seats',
          'SLA support',
        ],
        cta: 'Contact sales',
        contactSales: true,
        icon: Building2,
      },
    ],
  },
  {
    id: 'farm',
    label: 'Farm',
    icon: Sprout,
    color: '#3B6D11',
    tagline: 'Crop advisory, diagnosis, weather and yield tracking.',
    plans: [
      {
        id: 'farm_free',
        name: 'Free',
        price: '$0',
        priceNote: 'No credit card required',
        description: 'Basic advisory for a single farm.',
        features: [
          'One farm profile',
          'Limited photo diagnoses',
          'Local weather outlook',
        ],
        cta: 'Current plan',
        ctaDisabled: true,
        icon: Zap,
      },
      {
        id: 'farm_paid',
        name: 'Farm',
        priceMonthly: '$9.99',
        priceYearly: '$7.99',
        priceSuffix: '/month',
        priceNote: 'Cancel anytime',
        priceNoteYearly: 'Billed $95.88/year — save 20%',
        description: 'Full agronomist toolkit for your farms.',
        features: [
          'Unlimited farms and fields',
          'Unlimited photo diagnosis',
          'Weather alerts',
          'Crop yield tracking',
          'Advisory chat in your language',
          'Season reports',
        ],
        cta: 'Get Farm',
        popular: true,
        priceKey: 'farm_monthly',
        priceKeyYearly: 'farm_yearly',
        icon: Sprout,
      },
    ],
  },
];