import React, { useState, useContext } from 'react';
import { Circle, Download, ArrowLeftRight } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import StudioLayout from '@/components/studio/StudioLayout';
import Studio3DViewer from '@/components/studio/Studio3DViewer';
import RunModeTabs from '@/components/studio/RunModeTabs';
import SingleRunPanel from '@/components/studio/SingleRunPanel';
import BatchPanel from '@/components/studio/BatchPanel';
import PipelinePanel from '@/components/studio/PipelinePanel';
import { SourcedBadge, TrustLabel, downloadTextFile, StudioPageHeader, StudioSectionHeading } from '@/components/studio/StudioShared';
import AuthContext from '@/components/auth/AuthContext';
import XTBQuantumPanel from '@/components/studio/XTBQuantumPanel';
import DockingPanel from '@/components/studio/DockingPanel';

const INPUT_TYPES = [
  { value: 'name', label: 'Compound Name', placeholder: 'e.g. aspirin' },
  { value: 'smiles', label: 'SMILES', placeholder: 'e.g. CCO' },
  { value: 'cid', label: 'PubChem CID', placeholder: 'e.g. 702' },
  { value: 'cas', label: 'CAS Number', placeholder: 'e.g. 64-17-5' },
  { value: 'file', label: 'File Upload', placeholder: '' },
];

const d = r => r?.data?.data || r?.data || r;

function pubchemUrl(input, inputType, endpoint) {
  const enc = encodeURIComponent(input.trim());
  const props = 'MolecularWeight,XLogP,HBondDonorCount,HBondAcceptorCount,TPSA,RotatableBondCount,CanonicalSMILES';
  if (endpoint === 'properties') {
    if (inputType === 'smiles') return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/${enc}/property/${props}/JSON`;
    if (inputType === 'cid') return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${enc}/property/${props}/JSON`;
    return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${enc}/property/${props}/JSON`;
  }
  if (inputType === 'smiles') return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/${enc}/JSON`;
  if (inputType === 'cid') return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${enc}/JSON`;
  return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${enc}/JSON`;
}

function ResultShell({ result, children }) {
  return (
    <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="p-5">
        <div className="flex items-center justify-between mb-4">
          <SourcedBadge />
          <TrustLabel source={result.source} type={result.sourceType} />
        </div>
        {children}
      </div>
    </div>
  );
}

function DataTable({ data }) {
  if (!data || data.length === 0) return null;
  return (
    <div className="space-y-1.5">
      {data.map(([key, value], i) => (
        <div key={i} className="flex justify-between text-sm gap-2">
          <span className="text-slate-500">{key}</span>
          <span className="font-mono text-slate-800 text-right">{value}</span>
        </div>
      ))}
    </div>
  );
}

// Generate xTB input file from SDF
function generateXTBInput(sdfText, moleculeName) {
  const lines = sdfText.split('\n');
  const countsLine = lines[3] || '';
  const nAtoms = parseInt(countsLine.substring(0, 3)) || 0;
  const atoms = [];
  for (let i = 4; i < 4 + nAtoms && i < lines.length; i++) {
    const parts = lines[i].trim().split(/\s+/);
    if (parts.length >= 4) {
      atoms.push(`  ${parseFloat(parts[0]).toFixed(6).padStart(10)}  ${parseFloat(parts[1]).toFixed(6).padStart(10)}  ${parseFloat(parts[2]).toFixed(6).padStart(10)}  ${parts[3]}`);
    }
  }
  return `$title
  ${moleculeName} - generated by Suttain Computational Studio
$coord
${atoms.join('\n')}
$end
$opt
  maxcycle=200
  microcycle=50
$end
$gfn
  method=2
$end
`;
}

// Generate MOPAC PM7 input
function generatePM7Input(sdfText, moleculeName) {
  const lines = sdfText.split('\n');
  const countsLine = lines[3] || '';
  const nAtoms = parseInt(countsLine.substring(0, 3)) || 0;
  const atoms = [];
  for (let i = 4; i < 4 + nAtoms && i < lines.length; i++) {
    const parts = lines[i].trim().split(/\s+/);
    if (parts.length >= 4) {
      atoms.push(`${parts[3]}  ${parseFloat(parts[0]).toFixed(6)}  1  ${parseFloat(parts[1]).toFixed(6)}  1  ${parseFloat(parts[2]).toFixed(6)}  1`);
    }
  }
  return ` PM7 PRECISE GEO-OK
 ${moleculeName} - generated by Suttain Computational Studio

${atoms.join('\n')}
`;
}

const TOOLS = [
  {
    id: 'lookup',
    label: 'PubChem and ChEMBL Lookup',
    description: 'Search PubChem for compound identity, synonyms, and structural data',
    requiredInput: { type: 'name', hint: 'Compound name, SMILES, PubChem CID, or CAS number (e.g. aspirin, CCO, 702, 64-17-5)' },
    source: 'PubChem', sourceType: 'database',
    validate: ({ input }) => {
      if (!input || input.trim().length < 1) return 'Enter a compound name, SMILES, or CID.';
      return null;
    },
    handler: async ({ input, inputType }) => {
      const response = await fetch(pubchemUrl(input, inputType, 'full'));
      if (!response.ok) throw new Error(`PubChem lookup failed: ${response.status}. Check the compound name and try again.`);
      const data = await response.json();
      const compound = data?.PC_Compounds?.[0];
      if (!compound) throw new Error('No compound found for this query. Try a different name or SMILES.');
      const props = compound.props || [];
      const getProp = label => props.find(p => p.urn?.label === label)?.value;
      const cid = compound.id?.id?.cid;
      return {
        source: 'PubChem', sourceType: 'database', confidence: null,
        label: 'Compound identified from PubChem',
        imageUrl: cid ? `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${cid}/PNG` : null,
        data: [
          ['CID', cid || 'N/A'],
          ['Molecular formula', getProp('Molecular Formula')?.sval || 'N/A'],
          ['Molecular weight', getProp('Molecular Weight')?.fval || 'N/A'],
          ['IUPAC name', (getProp('IUPAC Name')?.sval || 'N/A').slice(0, 60)],
          ['Canonical SMILES', (getProp('Canonical SMILES')?.sval || getProp('SMILES')?.sval || 'N/A').slice(0, 60)],
          ['XLogP', getProp('XLogP')?.fval || 'N/A'],
        ],
        raw: { cid, formula: getProp('Molecular Formula')?.sval },
      };
    },
    renderResult: (result) => (
      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="grid md:grid-cols-2">
          <div className="border-b md:border-b-0 md:border-r border-slate-200 p-5 flex items-center justify-center" style={{ minHeight: 350 }}>
            {result.imageUrl
              ? <img src={result.imageUrl} alt="2D structure" className="max-w-full max-h-[300px]" />
              : <div className="flex items-center justify-center h-[300px] text-sm text-slate-400">2D structure unavailable</div>}
          </div>
          <div className="p-5">
            <div className="flex items-center justify-between mb-3">
              <SourcedBadge />
              <TrustLabel source={result.source} type={result.sourceType} />
            </div>
            <p className="text-sm font-semibold text-slate-800 mb-3">{result.label}</p>
            <DataTable data={result.data} />
            {result.raw?.cid && (
              <a href={`https://pubchem.ncbi.nlm.nih.gov/compound/${result.raw.cid}`} target="_blank" rel="noopener noreferrer"
                className="mt-4 inline-flex items-center gap-1.5 px-4 py-2 border border-slate-200 text-slate-600 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-colors">
                View on PubChem
              </a>
            )}
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'properties',
    label: 'Molecular Properties and Descriptors',
    description: 'Compute physicochemical properties and drug-likeness descriptors from PubChem',
    requiredInput: { type: 'name', hint: 'Compound name, SMILES, PubChem CID, or CAS number (e.g. aspirin, CCO, 702, 64-17-5)' },
    source: 'PubChem', sourceType: 'database',
    validate: ({ input }) => {
      if (!input || input.trim().length < 1) return 'Enter a compound name, SMILES, or CID.';
      return null;
    },
    handler: async ({ input, inputType }) => {
      const response = await fetch(pubchemUrl(input, inputType, 'properties'));
      if (!response.ok) throw new Error(`PubChem properties query failed: ${response.status}. Check the compound and try again.`);
      const data = await response.json();
      const p = data?.PropertyTable?.Properties?.[0];
      if (!p) throw new Error('No properties found for this compound. Try a different name or SMILES.');
      const hbd = p.HBondDonorCount ?? 0;
      const hba = p.HBondAcceptorCount ?? 0;
      const logp = p.XLogP ?? 0;
      const mw = parseFloat(p.MolecularWeight) || 0;
      const violations = (mw > 500 ? 1 : 0) + (logp > 5 ? 1 : 0) + (hbd > 5 ? 1 : 0) + (hba > 10 ? 1 : 0);
      return {
        source: 'PubChem', sourceType: 'database', confidence: null,
        label: 'Molecular properties retrieved from PubChem',
        imageUrl: p.CID ? `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${p.CID}/PNG` : null,
        data: [
          ['CID', p.CID || 'N/A'],
          ['Molecular weight', `${p.MolecularWeight || 'N/A'} g/mol`],
          ['XLogP', p.XLogP ?? 'N/A'],
          ['H-bond donors', hbd],
          ['H-bond acceptors', hba],
          ['TPSA', p.TPSA ? `${p.TPSA} A^2` : 'N/A'],
          ['Rotatable bonds', p.RotatableBondCount ?? 'N/A'],
          ['Lipinski violations', `${violations}/4 ${violations <= 1 ? '(drug-like)' : '(non drug-like)'}`],
        ],
        raw: p,
      };
    },
    renderResult: (result) => (
      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="grid md:grid-cols-2">
          <div className="border-b md:border-b-0 md:border-r border-slate-200 p-5 flex items-center justify-center" style={{ minHeight: 350 }}>
            {result.imageUrl
              ? <img src={result.imageUrl} alt="2D structure" className="max-w-full max-h-[300px]" />
              : <div className="flex items-center justify-center h-[300px] text-sm text-slate-400">2D structure unavailable</div>}
          </div>
          <div className="p-5">
            <div className="flex items-center justify-between mb-3">
              <SourcedBadge />
              <TrustLabel source={result.source} type={result.sourceType} />
            </div>
            <p className="text-sm font-semibold text-slate-800 mb-3">{result.label}</p>
            <DataTable data={result.data} />
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'gfn2xtb',
    label: 'GFN2-xTB and PM7 Input File Generation',
    description: 'Generate ready-to-run xTB and MOPAC PM7 input files from PubChem 3D structures for external execution',
    requiredInput: { type: 'name', hint: 'Compound name or SMILES (e.g. aspirin, CCO), a 3D structure is fetched from PubChem to build the input files' },
    source: 'External input files (xTB, MOPAC)', sourceType: 'external', engine: 'GFN2-xTB',
    validate: ({ input }) => {
      if (!input || input.trim().length < 1) return 'Enter a compound name or SMILES to generate input files.';
      return null;
    },
    handler: async ({ input, inputType }) => {
      const nameRes = await fetch(pubchemUrl(input, inputType || 'name', 'properties')).catch(() => null);
      let cid = null;
      if (nameRes && nameRes.ok) {
        const nameData = await nameRes.json();
        cid = nameData?.PropertyTable?.Properties?.[0]?.CID;
      }
      if (!cid) {
        const fullRes = await fetch(pubchemUrl(input, inputType || 'name', 'full'));
        if (fullRes.ok) {
          const fullData = await fullRes.json();
          cid = fullData?.PC_Compounds?.[0]?.id?.id?.cid;
        }
      }
      if (!cid) throw new Error('Could not find this compound on PubChem. Try a different name or SMILES.');
      const sdfRes = await fetch(`https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${cid}/SDF?record_type=3d`);
      if (!sdfRes.ok) throw new Error('No 3D structure available for this compound on PubChem.');
      const sdfText = await sdfRes.text();
      const xtbInput = generateXTBInput(sdfText, input.trim());
      const pm7Input = generatePM7Input(sdfText, input.trim());
      const atomCount = (sdfText.split('\n')[3] || '').substring(0, 3).trim();
      return {
        source: 'External input files (xTB, MOPAC)', sourceType: 'external', confidence: null,
        label: 'Input files generated for external execution',
        data: [
          ['PubChem CID', cid],
          ['Atoms in structure', atomCount || 'N/A'],
          ['xTB method', 'GFN2-xTB (extended tight-binding)'],
          ['PM7 method', 'MOPAC PM7 (semi-empirical)'],
          ['xTB run command', 'xtb molecule_xtb.inp --opt'],
          ['PM7 run command', 'mopac molecule_pm7.mop'],
          ['Note', 'These are input files for external execution, not computed energies'],
        ],
        files: [
          { filename: 'molecule_xtb.inp', content: xtbInput, label: 'xTB input (GFN2-xTB)' },
          { filename: 'molecule_pm7.mop', content: pm7Input, label: 'MOPAC input (PM7)' },
        ],
        raw: { cid, atomCount, xtbInput, pm7Input },
      };
    },
    renderResult: (result) => (
      <ResultShell result={result}>
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
          <p className="text-xs text-amber-700 font-semibold">
            Input files for external execution. GFN2-xTB and PM7 cannot run in a browser. Download these files and run them on your own infrastructure with xTB or MOPAC installed.
          </p>
        </div>
        <p className="text-sm font-semibold text-slate-800 mb-3">{result.label}</p>
        <DataTable data={result.data} />
        <div className="mt-4 space-y-2">
          {result.files?.map((file, i) => (
            <div key={i} className="flex items-center justify-between p-3 bg-slate-50 border border-slate-200 rounded-lg">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-semibold text-slate-700">{file.filename}</span>
                <span className="text-xs text-slate-400">{file.label}</span>
              </div>
              <button onClick={() => downloadTextFile(file.filename, file.content)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white rounded-lg" style={{ background: '#0F6E56' }}>
                <Download className="w-3 h-3" /> Download
              </button>
            </div>
          ))}
        </div>
        {result.raw?.xtbInput && (
          <details className="mt-3">
            <summary className="text-xs font-semibold text-slate-500 cursor-pointer hover:text-slate-700">Preview xTB input file</summary>
            <pre className="mt-2 text-xs font-mono text-slate-600 bg-slate-50 border border-slate-200 rounded-lg p-3 overflow-x-auto max-h-48">{result.raw.xtbInput}</pre>
          </details>
        )}
      </ResultShell>
    ),
  },
  {
    id: 'xtb_run',
    label: 'GFN2-xTB Real Quantum Calculation',
    description: 'Run a real GFN2-xTB optimize and energy job on a remote xTB engine. Returns the optimized 3D geometry, total energy, HOMO-LUMO gap, and dipole.',
    requiredInput: { type: 'name', hint: 'Compound name or SMILES (e.g. aspirin, CCO), the calculation runs on a remote xTB engine' },
    source: 'Rowan cloud xTB engine', sourceType: 'external', engine: 'GFN2-xTB',
    validate: ({ input, inputType }) => {
      if (!input || input.trim().length < 1) return 'Enter a compound name or SMILES to run the calculation.';
      if (inputType && !['name', 'smiles', 'file'].includes(inputType)) return 'xTB calculation accepts a compound name or SMILES. Use PubChem lookup for CID or CAS.';
      return null;
    },
    handler: async ({ input, inputType }) => {
      const payload = inputType === 'smiles' ? { smiles: input.trim() } : { query: input.trim() };
      const res = d(await base44.functions.invoke('computeXTB', payload));
      if (res.error) throw new Error(res.error);
      const r = res.result || {};
      const atoms = (r.optimized_geometry || []).map(a => ({ element: a.element, position: a.position }));
      return {
        source: 'Rowan cloud xTB engine', sourceType: 'external', engine: 'GFN2-xTB',
        confidence: null,
        label: `Real GFN2-xTB optimization for ${res.query || input.trim()}`,
        atoms,
        data: [
          ['Resolved SMILES', (res.resolved_smiles || 'N/A').slice(0, 50)],
          ['Method', res.method || 'GFN2-xTB'],
          ['Mode', res.mode || 'rapid'],
          ['Atoms optimized', r.n_atoms ?? 'N/A'],
          ['Total energy', r.total_energy_hartree != null ? `${r.total_energy_hartree.toFixed(6)} Eh` : 'N/A'],
          ['Total energy', r.total_energy_kcal_mol != null ? `${r.total_energy_kcal_mol} kcal/mol` : 'N/A'],
          ['HOMO-LUMO gap', r.homo_lumo_gap != null ? `${Number(r.homo_lumo_gap).toFixed(4)} Eh` : 'N/A'],
          ['Dipole', r.dipole != null ? `${Number(Array.isArray(r.dipole) ? r.dipole[0] : r.dipole).toFixed(3)} D` : 'N/A'],
          ['Compute location', 'Cloud (server-side xTB engine)'],
          ['Elapsed', res.provenance?.elapsed_seconds != null ? `${res.provenance.elapsed_seconds} s` : 'N/A'],
          ['Credits charged', res.provenance?.credits_charged ?? 'N/A'],
        ],
        honestyNote: res.honesty_note,
        raw: res,
      };
    },
    renderResult: (result) => (
      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="grid md:grid-cols-2">
          <div className="border-b md:border-b-0 md:border-r border-slate-200" style={{ minHeight: 350 }}>
            {result.atoms && result.atoms.length > 0
              ? <Studio3DViewer atoms={result.atoms} height={350} />
              : <div className="flex items-center justify-center h-[350px] text-sm text-slate-400">Optimized geometry unavailable</div>}
          </div>
          <div className="p-5">
            <div className="flex items-center justify-between mb-3">
              <SourcedBadge />
              <TrustLabel source={result.source} type={result.sourceType} />
            </div>
            <p className="text-sm font-semibold text-slate-800 mb-1">{result.label}</p>
            <p className="text-xs text-slate-500 mb-3">Optimized geometry rendered from the real xTB output.</p>
            <DataTable data={result.data} />
            {result.honestyNote && (
              <div className="mt-4 bg-violet-50 border border-violet-200 rounded-lg p-3">
                <p className="text-xs text-violet-700">{result.honestyNote}</p>
              </div>
            )}
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'comparison',
    label: 'Side-by-side Compound Comparison',
    description: 'Compare two compounds from PubChem with property differences highlighted',
    requiredInput: { type: 'name', hint: 'Two compounds, one per line (e.g. aspirin on the first line, ibuprofen on the second)' },
    source: 'PubChem', sourceType: 'database',
    validate: ({ input }) => {
      const lines = input.split('\n').map(s => s.trim()).filter(Boolean);
      if (lines.length < 2) return 'Enter two compounds, one per line, to compare them.';
      return null;
    },
    handler: async ({ input, inputType }) => {
      const [s1, s2] = input.split('\n').map(s => s.trim()).filter(Boolean);
      if (!s1 || !s2) throw new Error('Enter two compounds, one per line');
      const it = inputType === 'file' ? 'name' : inputType;
      const [r1, r2] = await Promise.all([
        fetch(pubchemUrl(s1, it, 'properties')).then(r => r.json()).catch(() => null),
        fetch(pubchemUrl(s2, it, 'properties')).then(r => r.json()).catch(() => null),
      ]);
      const p1 = r1?.PropertyTable?.Properties?.[0];
      const p2 = r2?.PropertyTable?.Properties?.[0];
      if (!p1) throw new Error(`Could not find compound: ${s1}`);
      if (!p2) throw new Error(`Could not find compound: ${s2}`);
      return {
        source: 'PubChem', sourceType: 'database', confidence: null,
        label: 'Compound comparison from PubChem',
        compoundA: { name: s1, props: p1, imageUrl: p1.CID ? `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${p1.CID}/PNG` : null },
        compoundB: { name: s2, props: p2, imageUrl: p2.CID ? `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${p2.CID}/PNG` : null },
        data: [
          ['CID', `${p1.CID || '?'} vs ${p2.CID || '?'}`],
          ['MW (g/mol)', `${p1.MolecularWeight || '?'} vs ${p2.MolecularWeight || '?'}`],
          ['XLogP', `${p1.XLogP ?? '?'} vs ${p2.XLogP ?? '?'}`],
          ['HBD', `${p1.HBondDonorCount ?? '?'} vs ${p2.HBondDonorCount ?? '?'}`],
          ['HBA', `${p1.HBondAcceptorCount ?? '?'} vs ${p2.HBondAcceptorCount ?? '?'}`],
          ['TPSA', `${p1.TPSA ?? '?'} vs ${p2.TPSA ?? '?'}`],
          ['Rotatable bonds', `${p1.RotatableBondCount ?? '?'} vs ${p2.RotatableBondCount ?? '?'}`],
        ],
        raw: { compound_a: p1, compound_b: p2 },
      };
    },
    renderResult: (result) => (
      <ResultShell result={result}>
        <div className="grid md:grid-cols-2 gap-4 mb-4">
          {[result.compoundA, result.compoundB].map((c, idx) => (
            <div key={idx} className="border border-slate-200 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <ArrowLeftRight className="w-4 h-4 text-slate-400" />
                <span className="font-semibold text-sm text-slate-700">{c.name}</span>
              </div>
              {c.imageUrl
                ? <img src={c.imageUrl} alt={`2D structure of ${c.name}`} className="max-w-full max-h-48 mx-auto" />
                : <div className="h-48 flex items-center justify-center text-sm text-slate-400">No image</div>}
            </div>
          ))}
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-slate-200">
                <th className="text-left py-2 px-3 font-semibold text-slate-500 text-xs uppercase tracking-wider">Property</th>
                <th className="text-right py-2 px-3 font-semibold text-slate-500 text-xs uppercase tracking-wider">{result.compoundA.name}</th>
                <th className="text-right py-2 px-3 font-semibold text-slate-500 text-xs uppercase tracking-wider">{result.compoundB.name}</th>
                <th className="text-right py-2 px-3 font-semibold text-slate-500 text-xs uppercase tracking-wider">Delta</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['MW', 'MolecularWeight', ' g/mol'],
                ['XLogP', 'XLogP', ''],
                ['HBD', 'HBondDonorCount', ''],
                ['HBA', 'HBondAcceptorCount', ''],
                ['TPSA', 'TPSA', ' A^2'],
                ['Rotatable', 'RotatableBondCount', ''],
              ].map(([label, key, unit]) => {
                const v1 = result.compoundA.props[key];
                const v2 = result.compoundB.props[key];
                const delta = (v1 != null && v2 != null) ? (parseFloat(v2) - parseFloat(v1)).toFixed(2) : 'N/A';
                const isDiff = delta !== 'N/A' && delta !== '0.00';
                return (
                  <tr key={key} className="border-b border-slate-100">
                    <td className="py-2 px-3 text-slate-500">{label}</td>
                    <td className="py-2 px-3 text-right font-mono text-slate-700">{v1 ?? 'N/A'}{unit}</td>
                    <td className="py-2 px-3 text-right font-mono text-slate-700">{v2 ?? 'N/A'}{unit}</td>
                    <td className={`py-2 px-3 text-right font-mono ${isDiff ? 'font-semibold text-violet-600' : 'text-slate-400'}`}>{delta}{isDiff ? unit : ''}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </ResultShell>
    ),
  },
];

const PIPELINE_STEPS = [
  { id: 'lookup', label: 'Compound Lookup', handler: TOOLS[0].handler },
  { id: 'properties', label: 'Property Computation', handler: TOOLS[1].handler },
  { id: 'gfn2xtb', label: 'GFN2-xTB Input File', handler: TOOLS[2].handler },
];

const API_CODE = `import requests

# Look up a compound from PubChem
response = requests.post(
    "https://api.suttain.com/v1/compound",
    headers={
        "Authorization": "Bearer YOUR_API_KEY",
        "Content-Type": "application/json"
    },
    json={
        "query": "CCO",
        "query_type": "smiles"
    }
)

data = response.json()
print(data)`;

export default function ComputationalStudioSmallMolecules() {
  const [activeMode, setActiveMode] = useState('single');
  const { user } = useContext(AuthContext);
  const isPro = user && (['pro', 'lifetime', 'pro_lifetime', 'academic'].includes(user.subscription_tier) || user.role === 'admin');
  const config = { inputTypes: INPUT_TYPES, tools: TOOLS, viewerMode: 'molecule', inputPlaceholder: 'Enter one SMILES or compound name per line' };

  return (
    <StudioLayout>
      <div className="space-y-6 py-4">
        <StudioPageHeader icon={Circle} title="Small Molecules" subtitle="PubChem lookup, molecular properties, real GFN2-xTB quantum calculation, xTB/PM7 input files, and compound comparison" badge={<SourcedBadge />} />
        <div className="bg-white border border-slate-200 rounded-xl p-6"><Studio3DViewer mode="molecule" height={300} /></div>
        <RunModeTabs active={activeMode} onChange={setActiveMode} />
        {activeMode === 'single' && <SingleRunPanel config={config} />}
        {activeMode === 'batch' && <BatchPanel config={config} isPro={isPro} />}
        {activeMode === 'pipeline' && <PipelinePanel config={{ steps: PIPELINE_STEPS, inputTypes: INPUT_TYPES, inputPlaceholder: 'Enter SMILES' }} isPro={isPro} />}

        <div className="border-t border-slate-200 pt-6 space-y-4">
          <StudioSectionHeading title="Quantum Geometry and Energy" subtitle="Run a real GFN2-xTB semi-empirical optimization on a cloud engine. The browser is the interface; heavy quantum compute runs server-side." />
          <XTBQuantumPanel />
        </div>

        <div className="border-t border-slate-200 pt-6 space-y-4">
          <StudioSectionHeading icon={ArrowLeftRight} title="Docking and binding analysis" subtitle="Predict ranked binding poses, docking scores, and interaction residues for a small molecule or protein ligand against a protein receptor." />
          <DockingPanel />
        </div>
      </div>
    </StudioLayout>
  );
}