import React from 'react';
export default function MaceParameterFields({engine,inputs,onChange,simType,section='all'}) {
  const advanced=section!=='core',core=section!=='advanced',task=inputs.engine_task || engine.tasks[0];
  const numeric=(key,label,value,min,max,step=1)=><div key={key}><label htmlFor={key}>{label}</label><input id={key} type="number" min={min} max={max} step={step} className="simulation-control" value={inputs[key] ?? value} onChange={e=>onChange(key,e.target.value===''?'':Number(e.target.value))}/></div>;
  return <section className="space-y-4 mb-7"><h3>MACE preparation parameters</h3>
    {!engine.sim_types.includes(simType) && <p role="status" className="text-sm text-destructive">MACE is not supported for this workflow.</p>}
    <div className="grid gap-4 sm:grid-cols-2">
      {core && <><div><label htmlFor="mace-model">Foundation model</label><select id="mace-model" className="simulation-control" value={inputs.engine_method || engine.methods[0]} onChange={e=>onChange('engine_method',e.target.value)}>{engine.methods.map(x=><option key={x}>{x}</option>)}</select></div><div><label htmlFor="mace-task">Prepared task</label><select id="mace-task" className="simulation-control" value={task} onChange={e=>onChange('engine_task',e.target.value)}>{engine.tasks.map(x=><option key={x}>{x}</option>)}</select></div></>}
      {advanced && <><div className="sm:col-span-2"><label htmlFor="mace-xyz">XYZ geometry (or use the compound input)</label><textarea id="mace-xyz" rows={6} className="simulation-control font-mono" value={inputs.geometry_xyz || ''} onChange={e=>onChange('geometry_xyz',e.target.value)} placeholder={'3\nWater\nO 0 0 0\nH 0 0 0.9572\nH 0.9266 0 -0.2396'}/></div><div><label htmlFor="mace-device">Local compute device</label><select id="mace-device" className="simulation-control" value={inputs.mace_device || 'cpu'} onChange={e=>onChange('mace_device',e.target.value)}><option value="cpu">CPU</option><option value="cuda">CUDA GPU</option></select></div><label className="flex items-center gap-2"><input type="checkbox" checked={inputs.mace_periodic===true} onChange={e=>onChange('mace_periodic',e.target.checked)}/>Periodic boundaries</label>
        {inputs.mace_periodic && <div className="sm:col-span-2"><label htmlFor="mace-cell">Cell vectors (nine components in angstroms)</label><input id="mace-cell" className="simulation-control font-mono" value={inputs.cell || ''} onChange={e=>onChange('cell',e.target.value)} placeholder="12 0 0 0 12 0 0 0 12"/></div>}
        {task==='Geometry optimization' && <>{numeric('mace_fmax','Force threshold (eV/angstrom)',0.05,0.0001,1,0.001)}{numeric('mace_opt_steps','Maximum optimization steps',200,1,10000)}</>}
        {task==='Molecular dynamics' && <><div><label htmlFor="mace-ensemble">Ensemble</label><select id="mace-ensemble" className="simulation-control" value={inputs.mace_ensemble || 'NVT'} onChange={e=>onChange('mace_ensemble',e.target.value)}><option>NVT</option><option>NVE</option></select></div>{numeric('mace_temperature','Initial / NVT temperature (K)',300,1,5000)}{numeric('mace_steps','MD steps',1000,1,1000000)}{numeric('mace_timestep_fs','Timestep (fs)',0.5,0.01,5,0.01)}</>}
      </>}
    </div><p className="text-sm text-research-muted">Local ASE scripts only, not hosted compute or fresh DFT. OFF23 supports neutral organic systems and has academic checkpoint licensing; MP-0 targets materials. No basis set or implicit solvent applies.</p>
  </section>;
}