import { RISK_STYLE } from '@/components/drug-design/discoveryData';
import CandidateProperties from '@/components/drug-design/CandidateProperties';
import ScreeningResultSummary from '@/components/drug-design/ScreeningResultSummary';
export default function DiscoveryCandidates({ state: s }) {
  const count = Object.values(s.selected).filter(Boolean).length;
  return <section aria-labelledby="discovery-candidates-title">
    <h1 id="discovery-candidates-title" className="mb-1">Design candidates</h1>
    <p className="text-muted-foreground mb-4">Computed ChEMBL screening results—not docking or validated ADMET</p>
    {s.jobs.isPending ? <p role="status">Loading your screening results…</p> : s.jobs.isError ? <p role="alert">Could not load screening results. <button onClick={s.refresh} className="underline">Retry</button></p> : !s.candidateJob ? <div className="border border-border rounded-lg p-6"><p className="mb-4">No screening results yet. Launch a screening to calculate candidate properties and similarity.</p><button onClick={() => s.navigate('new', 0)} className="research-secondary">Define a target →</button></div> : <>
      <ScreeningResultSummary job={s.candidateJob} />
      <div className="flex flex-wrap gap-3 items-end justify-between mb-4"><div className="flex flex-wrap gap-3">
        <div><label htmlFor="drug-risk" className="text-xs block mb-1">Estimated property-rule risk</label><select id="drug-risk" value={s.riskFilter} onChange={e => s.setRiskFilter(e.target.value)} className="simulation-control"><option value="all">All rule risk</option><option value="low">Low only</option><option value="exclude_high">Exclude high risk</option></select></div>
        <div><label htmlFor="drug-sort" className="text-xs block mb-1">Sort candidates</label><select id="drug-sort" value={s.sortBy} onChange={e => s.setSortBy(e.target.value)} className="simulation-control"><option value="score">Similarity</option><option value="mw">Molecular weight</option><option value="risk">Rule violations</option></select></div>
      </div><p className="text-xs text-muted-foreground" aria-live="polite">{s.visibleCandidates.length} candidates</p></div>
      {s.visibleCandidates.length === 0 ? <p className="text-sm text-muted-foreground">No candidates match the selected filters. Use a less restrictive filter or launch another screening.</p> : <div className="overflow-x-auto"><table className="w-full text-sm min-w-[640px]"><caption className="sr-only">Computed ChEMBL compounds, path-based similarity and estimated property-rule risk</caption><thead><tr className="text-left text-xs text-muted-foreground border-b border-border">{['Select', 'Compound & properties', 'Similarity proxy (0–1)', 'Rule risk'].map(label => <th key={label} scope="col" className="p-2">{label}</th>)}</tr></thead><tbody>{s.visibleCandidates.map(c => <tr key={c.id} className="border-b border-border hover:bg-muted"><td className="p-2 align-top"><input type="checkbox" aria-label={`Select ${c.id}`} checked={!!s.selected[c.id]} onChange={() => s.toggleSelect(c.id)} /></td><th scope="row" className="p-2 font-normal text-left"><a href={`https://www.ebi.ac.uk/chembl/explore/compound/${encodeURIComponent(c.id)}`} target="_blank" rel="noreferrer" className="font-medium text-primary underline">{c.drug}</a><p className="text-xs text-muted-foreground">{c.id}{c.is_reference ? ' · Known reference ligand' : ''}</p><CandidateProperties candidate={c} /></th><td className="p-2 align-top font-mono">{typeof c.binding_proxy_score === 'number' ? c.binding_proxy_score.toFixed(4) : 'Not calculated'}</td><td className="p-2 align-top"><span className={`text-xs px-2 py-1 rounded font-mono ${RISK_STYLE[c.risk]}`}>{c.risk}</span></td></tr>)}</tbody></table></div>}
      <p className="text-xs text-muted-foreground mt-4">Similarity proxy = best Tanimoto match to a reference ligand, not binding affinity. Low rule risk is not evidence of safety. LogP/TPSA are reduced-fragment estimates.</p>
    </>}
    {s.actionError && <p role="alert" className="mt-3 text-sm text-destructive">{s.actionError}</p>}
    {s.shortlistError && <p role="alert" className="mt-3 text-sm text-destructive">Could not load your saved shortlist. <button onClick={s.refresh} className="underline">Retry</button></p>}
    {count > 0 && <div className="sticky bottom-0 mt-4 bg-foreground text-background rounded-lg p-4 flex flex-wrap gap-3 items-center justify-between"><span className="text-sm" aria-live="polite">{count} selected (including filtered-out rows)</span><button onClick={s.addSelectedToShortlist} disabled={s.saving || s.shortlistLoading || !!s.shortlistError} className="research-primary bg-primary text-primary-foreground disabled:opacity-40">{s.saving ? 'Saving…' : 'Save & compare selected →'}</button></div>}
  </section>;
}